### ISSUE TITLE
Wonky internet connection results in mapbox-studio 0.2.0 crashes 

### ISSUE THREAD

**Issue by artemp** [mapbox/mapbox-studio-classic#1047]
``` bash
Error: Timed out after 5000ms
    at Get.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:179:27)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1801:10)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at Socket._onTimeout (net.js:326:8)
    at Timer.unrefTimeout [as ontimeout] (timers.js:427:13)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "vector_tile.Tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "vector_tile.Tile" because it is missing required fields: (cannot determine missing fields for lite message)

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
```

**Comment by springmeyer** [comment]
Just hit this at startup on windows. The app tried to load for a few seconds then crashed. Refs #645

**Comment by springmeyer** [comment]
Interestingly I intentionally disconnected my internet connection to try to replicate the crash. In this case instead of the whole application going down I saw `Timed out after 5000ms` displayed on a blue atom-shell window. So, not sure what is different that would cause a full crash and abrupt application in one case but not in the other.

**Comment by wilhelmberg** [comment]
> So, not sure what is different that would cause a full crash and abrupt application in one case but not in the other.

Difference is:
_no connection at all_ versus _intermittent connection with possibly corrupted data_.

The latter is a nightmare to debug: I once faced a cooperate firewall that let all requests pass, but deleted some parts of some request bodies that it deemed dangerous. Image the time it took to figure _that_ out.

I tried to simulate bad connection with [Fiddler](http://www.telerik.com/fiddler) and [Clumsy](http://jagt.github.io/clumsy/).
Was not able to reproduce error/crash.

Although it seems to happen the first time I start Studio after a fresh boot. Although not consistently.

**Comment by yhahn** [comment]
I've always assumed this was an upstream issue where a closed connection by the server could lead to incomplete payloads because node's core does not check the content length header for you. (Note I could not find any similar check in request either).

Implemented a check in node-get here:

https://github.com/mapbox/node-get/pull/17

Will look at more testing + release today.

**Comment by springmeyer** [comment]
thank you @yhahn. To make sure I understand do you think checking content length and handling that error would address both `Error: Timed out after 5000ms`, `Can't parse message of type "vector_tile.Tile" because it is missing required fields`, and `Can't set headers after they are sent.`? I notice All three are showing up above. The only one I saw in the startup crash was `Error: Timed out after 5000ms`. It is not clear to me yet if and how they are always connected.

**Comment by yhahn** [comment]
I'm not sure it will solve any of these cases for sure other than turning #2 into a different error.

I get the impression that 2+3 are caused by some bad error handling somewhere in our stack where a callback is getting called twice where it should be getting called once. It might only be triggered in the protobuf parse failure case though, so it's possible it will be fixed by this change.

**Comment by springmeyer** [comment]
okay, thanks, makes sense and sounds good to focus on getting in front of the protobuf parse error.
