### ISSUE TITLE
Failed to upload a part to S3: The provided token has expired

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-studio-classic#1082]
Error dump:

<pre><code>
Mapbox Studio @ http://localhost:3000/
Error: Failed to upload a part to S3: {"message":"write EPIPE","code":"NetworkingError","errno":"EPIPE","syscall":"write","region":"us-east-1","hostname":"tilestream-tilesets-production.s3.amazonaws.com","retryable":true,"time":"2014-12-01T14:22:48.833Z","statusCode":400}
 Additionally failed to abort the multipart upload on S3: ExpiredToken: The provided token has expired.
    at Writable.<anonymous> (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/index.js:124:17)
    at Writable.emit (events.js:117:20)
    at Response.<anonymous> (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:249:21)
    at Request.<anonymous> (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
    at Request.callListeners (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.failRequest (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:498:10)
    at Request.<anonymous> (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:484:32)
    at Request.<anonymous> (/Users/kristianfallro/Projects/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:541:20)

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! mapbox-studio@0.2.0 start: `./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapbox-studio@0.2.0 start script.
npm ERR! This is most likely a problem with the mapbox-studio package,
npm ERR! not with npm itself.

</code></pre>

Data source: Roughly 2 GB of PostGIS data

Will try to run a mbtiles export as well.

**Comment by springmeyer** [comment]
Thanks for the report. Yes, please try again and let us know how it goes. Also I see you are building from source - can you confirm which git revision you are built from?

**Comment by kristfal** [comment]
It is: mapbox-studio@0.2.0

**Comment by yhahn** [comment]
@kristfal after how long did the upload fail? The current upload credentials from the mapbox API expire after 12 hours I think which may be too short in some cases -- if this is what you ran into I can look at increasing the expiration time.

**Comment by kristfal** [comment]
Less than 6 hours, probably roughly 4.

**Comment by kristfal** [comment]
Finshed building the mbtiles locally without any failure. The build indicator stopped at 3,9% before it jumped to 100%, but other than that, everything worked.

Total datasize: 310 MB
Build time: Roughly 2 hours

**Comment by willwhite** [comment]
We fix a regression on the Mapbox API side that we issuing credentials with shorter expirations. This should be fixed now.
