### ISSUE TITLE
Failed to upload to S3 error and crash

### ISSUE THREAD

**Issue by orthodoc** [mapbox/mapbox-studio-classic#1089]
When I attempt to upload a data source to mapbox through studio, the progress bar hangs on at 0.1% for a long time. After a while it crashes with no output.

Error log is as follows:

```
188 Mapbox Studio @ http://localhost:3000/
189 Error: Failed to upload a part to S3: {"message":"The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or
190     at Writable.<anonymous> (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/index.js:124:17)
191     at Writable.emit (events.js:117:20)
192     at Response.<anonymous> (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:251:21)
193     at Request.<anonymous> (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
194     at Request.callListeners (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
195     at Request.emit (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
196     at Request.emitEvent (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
197     at Request.<anonymous> (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:488:14)
198     at Request.emitEvents (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:509:20)
199     at Request.<anonymous> (/home/bdb/mapbox/resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:516:16)
```

Only if I reduce the zoom range to 16 or below, does a successful upload happen in an inconsistent way.
Mapbox Studio v 0.2.0
Ubuntu 14.04 64 bit on Apple MBA

**Comment by orthodoc** [comment]
This is what I did to overcome the problem:

Reduced the lower end of the zoom leve insteadl. Installed mapbox-studio via node. Exported the project to mbtiles. Downloaded the mbtiles file to the hard drive. Must mention here that this was not happening when working with the binary distribution. A big file that took some time uploading to the mapbox account. Direct uploading to the mapbox account still fails with a similar message as above.
