### ISSUE TITLE
Studio crashing during upload, S3 related?

### ISSUE THREAD

**Issue by savannahjune** [mapbox/mapbox-studio-classic#1102]
Hello,

Studio is crashing for me while I try to upload a source.  It's happened four times at this point, and I've pasted the application logs below.

Thanks,
Savannah

```
Mapbox Studio @ http://localhost:3000/
Error: Failed to upload a part to S3: {"message":"write EPIPE","code":"NetworkingError","errno":"EPIPE","syscall":"write","region":"us-east-1","hostname":"tilestream-tilesets-production.s3.amazonaws.com","retryable":true,"time":"2014-12-10T20:26:43.933Z","statusCode":400}
 Additionally failed to abort the multipart upload on S3: ExpiredToken: The provided token has expired.
    at Writable.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/index.js:124:17)
    at Writable.emit (events.js:117:20)
    at Response.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:249:21)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
    at Request.callListeners (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.failRequest (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:498:10)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:484:32)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:541:20)
Mapbox Studio @ http://localhost:3000/
Error: Failed to upload a part to S3: {"message":"The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.","code":"NoSuchUpload","time":"2014-12-10T23:00:48.137Z","statusCode":404,"retryable":false}
    at Writable.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/index.js:124:17)
    at Writable.emit (events.js:117:20)
    at Response.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:251:21)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
    at Request.callListeners (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:488:14)
    at Request.emitEvents (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:509:20)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:516:16)
Mapbox Studio @ http://localhost:3000/
Error: Failed to upload a part to S3: {"message":"write EPIPE","code":"NetworkingError","errno":"EPIPE","syscall":"write","region":"us-east-1","hostname":"tilestream-tilesets-production.s3.amazonaws.com","retryable":true,"time":"2014-12-11T00:24:37.257Z","statusCode":400}
 Additionally failed to abort the multipart upload on S3: ExpiredToken: The provided token has expired.
    at Writable.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/index.js:124:17)
    at Writable.emit (events.js:117:20)
    at Response.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:249:21)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
    at Request.callListeners (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.failRequest (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:498:10)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:484:32)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:541:20)
Mapbox Studio @ http://localhost:3000/
Error: Failed to upload a part to S3: {"message":"write EPIPE","code":"NetworkingError","errno":"EPIPE","syscall":"write","region":"us-east-1","hostname":"tilestream-tilesets-production.s3.amazonaws.com","retryable":true,"time":"2014-12-11T23:31:51.058Z","statusCode":400}
 Additionally failed to abort the multipart upload on S3: ExpiredToken: The provided token has expired.
    at Writable.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/index.js:124:17)
    at Writable.emit (events.js:117:20)
    at Response.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:249:21)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
    at Request.callListeners (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.failRequest (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:498:10)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:484:32)
    at Request.<anonymous> (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:541:20)
Mapbox Studio @ http://localhost:3000/
```

**Comment by mkawalec** [comment]
I'm getting the same error on linux
