### ISSUE TITLE
Can't access auth screen

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#1138]
I'm not convinced it's unrelated to #1137, but just had studio blow up after updating. The process:
- `git pull`
- `npm start` gave me this:

``` console
module.js:340
    throw err;
          ^
Error: Cannot find module 'mapbox-machine-styles'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Volumes/Faraday3/github/mapbox-studio/lib/style.js:537:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! mapbox-studio@0.2.2 start: `./index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the mapbox-studio@0.2.2 start script.
npm ERR! This is most likely a problem with the mapbox-studio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapbox-studio
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Volumes/Faraday3/github/mapbox-studio
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Volumes/Faraday3/github/mapbox-studio/npm-debug.log
npm ERR! not ok code 0
```
- `npm install` gave me this:

``` console
| /Volumes/Faraday3/github/mapbox-studio @ Williams-MacBook-Pro (wboykinm) 
| => npm install

> mapbox-studio@0.2.2 preinstall /Volumes/Faraday3/github/mapbox-studio
> node scripts/run.js scripts/vendor-node.sh

Running /Volumes/Faraday3/github/mapbox-studio/scripts/vendor-node.sh
NOTICE: NODE_VERSION environment variable not defined, defaulting to 0.10.33
NOTICE: TARGET_ARCH environment variable not defined, defaulting to x64
Requested node version: 0.10.33
Requested node platform+arch: darwin-x64
Requested bin only: true
Verifying nodejs shasum
03e72005a4ed612aa7a984d840f148bfb76f3c5f  node-v0.10.33-darwin-x64.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3642  100  3642    0     0   7132      0 --:--:-- --:--:-- --:--:--  7141
WARNING: gpg not found. Installing node without verifying SHASUMS.txt.asc

npm WARN package.json dirty@0.9.9 No repository field.
npm WARN package.json mapbox-studio-default-source@1.0.0 No repository field.
npm WARN package.json mapbox-studio-default-style@1.0.0 No repository field.
npm WARN package.json mapbox-studio-comic@1.0.1 No repository field.
npm WARN package.json mapbox-studio-highcontrast@1.0.6 No repository field.
npm WARN package.json mapbox-studio-pirates@1.0.0 No repository field.
npm WARN package.json mapbox-studio-osm-bright@1.0.2 No repository field.
npm WARN package.json mapbox-studio-satellite-afternoon@1.0.1 No repository field.
npm WARN package.json mapbox-studio-wheatpaste@1.0.1 No repository field.
npm WARN package.json mapbox-studio-run-bike-and-hike@1.0.2 No repository field.
npm WARN package.json mapbox-studio-pencil@1.0.1 No repository field.
npm WARN package.json mapbox-studio-mapbox-outdoors@2.0.0 No repository field.
npm WARN package.json mapbox-studio-light@1.1.0 No repository field.
-
> mapbox-studio@0.2.2 postinstall /Volumes/Faraday3/github/mapbox-studio
> npm dedupe node-pre-gyp

npm WARN unavoidable conflict node-pre-gyp { '/Volumes/Faraday3/github/mapbox-studio/node_modules/mapnik/node_modules/node-pre-gyp': '0.6.1',
npm WARN unavoidable conflict   '/Volumes/Faraday3/github/mapbox-studio/node_modules/mapnik-omnivore/node_modules/srs/node_modules/node-pre-gyp': '0.6.1',
npm WARN unavoidable conflict   '/Volumes/Faraday3/github/mapbox-studio/node_modules/mapnik-omnivore/node_modules/gdal/node_modules/node-pre-gyp': '0.6.1',
npm WARN unavoidable conflict   '/Volumes/Faraday3/github/mapbox-studio/node_modules/node-pre-gyp': '0.6.1' }
npm WARN unavoidable conflict Not de-duplicating
npm WARN unmet dependency /Volumes/Faraday3/github/mapbox-studio/node_modules/mbtiles/node_modules/sqlite3 requires node-pre-gyp@'~0.5.27' but will load
npm WARN unmet dependency /Volumes/Faraday3/github/mapbox-studio/node_modules/node-pre-gyp,
npm WARN unmet dependency which is version 0.6.1
mapbox-machine-styles@2.3.0 node_modules/mapbox-machine-styles
├── mapbox-studio-dark@1.0.1
├── mapbox-studio-high-contrast@1.0.6
├── mapbox-studio-osm-bright@1.0.3
├── mapbox-studio-outdoors@2.0.0
├── mapbox-studio-streets-satellite@2.0.0
├── mapbox-studio-emerald@1.0.0
├── mapbox-studio-run-bike-hike@1.0.2
├── mapbox-studio-streets-basic@5.1.1
└── mapbox-studio-streets@5.1.2
```
- then another `npm start` and visit to localhost:3000 auto-directed me to an apparently-dead project:

![2015-01-16_1602](https://cloud.githubusercontent.com/assets/735463/5784339/59184202-9d99-11e4-840e-8df8d41c393d.png)
- closing the error changed the URL to localhost:3000/authorize, but didn't change the screen, and hit the console with this fun stuff:

``` console
Mapbox Studio @ http://localhost:3000/
500 'GET' '/style?id=tmstyle:///Volumes/Faraday3/github/map-demos/mapbox-studio/Sat2.tm2' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/style?id=tmstyle:///Volumes/Faraday3/github/map-demos/mapbox-studio/Sat2.tm2' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/style?id=tmstyle:///Volumes/Faraday3/github/map-demos/mapbox-studio/Sat2.tm2' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/style?id=tmstyle:///Volumes/Faraday3/github/map-demos/mapbox-studio/Sat2.tm2' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/style?id=tmstyle:///Volumes/Faraday3/github/map-demos/mapbox-studio/Sat2.tm2' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
500 'GET' '/authorize' 'Error: ENOENT, open \'/Volumes/Faraday3/github/mapbox-studio/node_modules/mapbox-machine-styles/node_modules/mapbox-studio-comic/project.yml\''
```

Time to use the mac package, or can I keep using the repo for updates?

**Comment by yhahn** [comment]
@wboykinm try

```
rm -rf node_modules
npm install
```

We had a little dependency musical chairs.

**Comment by wboykinm** [comment]
zing.

![2015-01-16_1615](https://cloud.githubusercontent.com/assets/735463/5784556/fc6bcb94-9d9a-11e4-8a23-10f8f1245662.png)

Thanks @yhahn!
