### ISSUE TITLE
Mapnik failure on reinstall

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-studio-classic#1296]
I've been running mapbox studio for a year now on my mac, pulling updates to my local repo and reinstalling as necessary. Unfortunately it looks like I may have just blown things up today - I pulled updates and tried to start but it threw this:

`Error: Cannot find module '/Volumes/Faraday3/github/mapbox-studio/node_modules/mapnik/lib/binding/node-v14-darwin-x64/mapnik_settings.js'`

So I cleared out `node_modules` and tried to reinstall, but after about 15 minutes and lots of warnings the process failed. Here's the log:

``` console
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/opt/nvm/versions/v0.12.1/bin/node',
1 verbose cli   '/usr/local/opt/nvm/versions/v0.12.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose node symlink /usr/local/opt/nvm/versions/v0.12.1/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart mapbox-studio@0.2.7
7 info start mapbox-studio@0.2.7
8 verbose unsafe-perm in lifecycle true
9 info mapbox-studio@0.2.7 Failed to exec start script
10 verbose stack Error: mapbox-studio@0.2.7 start: `./index.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/nvm/0.17.2/versions/v0.12.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/nvm/0.17.2/versions/v0.12.1/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid mapbox-studio@0.2.7
12 verbose cwd /Volumes/Faraday3/github/mapbox-studio
13 error Darwin 14.1.0
14 error argv "/usr/local/opt/nvm/versions/v0.12.1/bin/node" "/usr/local/opt/nvm/versions/v0.12.1/bin/npm" "start"
15 error node v0.12.1
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error mapbox-studio@0.2.7 start: `./index.js`
18 error Exit status 1
19 error Failed at the mapbox-studio@0.2.7 start script './index.js'.
19 error This is most likely a problem with the mapbox-studio package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     ./index.js
19 error You can get their info via:
19 error     npm owner ls mapbox-studio
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

Any chance this is related to #1209 - since I'm using 0.12.1 locally?

**Comment by springmeyer** [comment]
Right, we don't support node v0.12.x yet, so if you are building yourself with `npm install` do make sure you are using v0.10.x. After that I also recommend watching for when #1287 lands. Until it does there is another potential breakage related to duplicate node-mapnik versions getting placed with `npm install`.

**Comment by wboykinm** [comment]
@springmeyer Got it - that worked; thanks!
