### ISSUE TITLE
After loading a remote project and zooming out I get a https not supported. Expected "http" error

### ISSUE THREAD

**Issue by simudream** [mapbox/mapbox-studio-classic#1305]
This error is happening on my yosemite mac running latest brew node

sudo npm start

> mapbox-studio@0.2.7 start /Users/paul/Documents/mapbox-studio
> ./index.js
> HERE IS THE ERROR MESSAGE:
> <Sun, 05 Apr 2015 05:18:05 GMT> Mapbox Studio @ http://localhost:3000/
> _http_client.js:75
>     throw new Error('Protocol "' + protocol + '" not supported. ' +
>           ^
> Error: Protocol "https:" not supported. Expected "http:".
>     at new ClientRequest (_http_client.js:75:11)
>     at Object.exports.request (http.js:49:10)
>     at Object.exports.request (https.js:136:15)
>     at Get.request (/Users/paul/Documents/mapbox-studio/node_modules/tilejson/node_modules/get/lib/index.js:92:22)
>     at Get.perform (/Users/paul/Documents/mapbox-studio/node_modules/tilejson/node_modules/get/lib/index.js:132:30)
>     at Get.asBuffer (/Users/paul/Documents/mapbox-studio/node_modules/tilejson/node_modules/get/lib/index.js:298:10)
>     at CachingSource.TileJSON.get (/Users/paul/Documents/mapbox-studio/node_modules/tilejson/lib/tilejson.js:211:19)
>     at CachingSource.TileJSON.getTile (/Users/paul/Documents/mapbox-studio/node_modules/tilejson/lib/tilejson.js:142:10)
>     at /Users/paul/Documents/mapbox-studio/lib/cache.js:58:38
>     at Statement.<anonymous> (/Users/paul/Documents/mapbox-studio/node_modules/mbtiles/lib/mbtiles.js:150:20)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
npm ERR! mapbox-studio@0.2.7 start: `./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapbox-studio@0.2.7 start script './index.js'.
npm ERR! This is most likely a problem with the mapbox-studio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapbox-studio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/paul/Documents/mapbox-studio/npm-debug.log

**Comment by simudream** [comment]
problem on my end closing issue
