### ISSUE TITLE
TypeError: Cannot set property 'xml' of undefined

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-studio-classic#1319]
Rapidly loading the new project page, such as http://localhost:3000/new/style?id=tmpstyle:///Users/willwhite/mapbox-studio/node_modules/mapbox-studio-default-style can trigger the following crash:

```
/Users/willwhite/mapbox-studio/lib/style.js:115
        cache[id].xml = xml;
                      ^
TypeError: Cannot set property 'xml' of undefined
    at done (/Users/willwhite/mapbox-studio/lib/style.js:115:23)
    at /Users/willwhite/mapbox-studio/node_modules/tilelive-vector/index.js:112:20
```

![crash](https://cloud.githubusercontent.com/assets/93564/7275835/6f38ae1a-e906-11e4-9921-b22084c28270.gif)

**Comment by springmeyer** [comment]
I'm not sure if this hits the same codepath (or even invokes sources) but if it does https://github.com/mapbox/mapbox-studio/issues/1284 might be related.
