### ISSUE TITLE
Upgrading mapbox-studio-default-style breaks tests

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-studio-classic#1430]
If `mapbox-studio-default-style` is bumped from 1.x to 2.x then this breaks the tests like:

```
# mapbox-studio-default-style
not ok 1 Error: Server returned HTTP 404
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [Error: Server returned HTTP 404] status: 404 }
    at: error (/Users/dane/projects/mbstudio/node_modules/tilejson/node_modules/get/lib/index.js:294:9)
    stack: |-
      Error: Server returned HTTP 404
          at Get.handleClientRequest (/Users/dane/projects/mbstudio/node_modules/tilejson/node_modules/get/lib/index.js:151:23)
          at ClientRequest.g (events.js:180:16)
          at ClientRequest.emit (events.js:95:17)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
          at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
          at Socket.socketOnData [as ondata] (http.js:1584:20)
          at TCP.onread (net.js:528:27)
  ...

/Users/dane/projects/mbstudio/test/style-examples.test.js:32
            t.ok(!s.data._prefs.mapid, 'no mapid set');
                   ^
TypeError: Cannot read property 'data' of undefined
    at /Users/dane/projects/mbstudio/test/style-examples.test.js:32:20
    at /Users/dane/projects/mbstudio/lib/style.js:103:25
    at /Users/dane/projects/mbstudio/lib/style.js:194:25
    at /Users/dane/projects/mbstudio/lib/source.js:101:25
    at /Users/dane/projects/mbstudio/lib/source.js:463:29
    at error (/Users/dane/projects/mbstudio/node_modules/tilejson/node_modules/get/lib/index.js:294:9)
    at Get.<anonymous> (/Users/dane/projects/mbstudio/node_modules/tilejson/node_modules/get/lib/index.js:299:25)
    at Get.handleClientRequest (/Users/dane/projects/mbstudio/node_modules/tilejson/node_modules/get/lib/index.js:153:29)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
```

What appears to be the cause is that tilelive cannot fetch the `mapbox://mapbox-streets-v6` added in: https://github.com/mapbox/mapbox-studio-default-style/commit/b91d133dde2d62c564071fdcb8330cefc9cf8b66

@yhahn @ajashton - any idea why this would be (why v6 fetch would fail?)

**Comment by yhahn** [comment]
Yes, we currently mock the Mapbox API for our tests -- this mapid would need to be provided in https://github.com/mapbox/mapbox-studio/tree/mb-pages/test/fixtures-mapboxapi (or we could/should switch to encrypted creds and real use of Mapbox API).

**Comment by springmeyer** [comment]
going to stick with v5 styles right now, so will revert the above commit.

**Comment by springmeyer** [comment]
revert done in https://github.com/mapbox/mapbox-studio/commit/4218ea49c1b5a352bcffea4a83bb388b9f9d4cfb

**Comment by springmeyer** [comment]
followup revert to keep the tests passing https://github.com/mapbox/mapbox-studio/commit/e9a8fdf3d8c68d0f831a4e80540e9e62fbfbe068
