### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by inclanfunk** [mapbox/mapbox-studio-classic#1466]
After upgrading from version 2.8 to 3, Mapbox Studio would not start. I un-install, re-install the ultimate version several times, restart the computer but nothing will do. I also try to run the soft with Admin privileges without success.
I have been reading post relative to the .mapbox-studio folder and app.db but in my case, the folder does not even exist.
When I try to launch the app, the first loading screen briefly appears and fade out (I remember having the same issue when trying to lauch a previous 64 bits version on my 32 bits machine).

I am running Windows 7 32 bits.

**Comment by ferranferrer** [comment]
Hi everyone
I had same problem this morning when upgrading from 2.8 to 3.0. I use windows 8.1 64 bits.
I'm going to try the following solution.

Regards

**Comment by inclanfunk** [comment]
Which following solution?

**Comment by ferranferrer** [comment]
Sorry
This
https://github.com/mapbox/mapbox-studio-classic/issues/1384
But didn't work.
Obviously dll were version related and didn't function on Mp 3.0.

**Comment by wilhelmberg** [comment]
The workaround described in #1384 is **not valid** for `0.3.0`!
Please remove all files, that were extracted from the zip linked there.

---

Try the following steps instead:
- look into `%USERPROFILE%\.mapbox-studio` (<- paste this into the address bar of file explorer)
- if there is an `app.db.compacted`, delete it
- check via Task Manager that there are no running processes of
  - `node.exe` or
  - `mapbox-studio.exe`
- if there are, kill them
- open a command prompt:  (Windows key + r, type `cmd`, press ENTER)
  - type: `cd C:\Program Files\mapbox-studio\resources\app`
  - type: `vendor\node index.js`

Is there an error message or `Mapbox Studio @ http://localhost:3000/`?
- If there is an error message, please post it here.
- If it shows `Mapbox Studio @ http://localhost:3000/` open your browser at http://localhost:3000/
  - check if Mapbox Studio Classic works in your browser
  - **when you are done testing, go back to the console, press `Ctrl+C` to stop Mapbox Studio!!**
  - check if Mapbox Studio now works via the Application shortcut.

**Comment by ferranferrer** [comment]
Thanks Berg.
This worked it.
I have a personal Mapbox account and also working in a Client's account.
I have followed your instructions -the last ones ;-)- and Mapbox runned ok but I had 'connection not allowed' message when tried to connect. See below images.
Then I came back to web Mapbox studio and reset my password and succesfully connected with Mapbox Studio desktop with my account. After this I close and restarted and connected with my client's provided user credentials.
Now all is working fine, for now,
I remember taht last session -threee days ago- that I had problems to uploads style to my client's Mapbox web, so I continued working in a local folder. Now I have uploaded without problems.

This is only my opinion, but seems that version change and 'possiblly' working with 2 Mapbox accounts during it crashes the new installation.

Thanks for your solutions.
And thanks again. 
Ferran

![error1](https://cloud.githubusercontent.com/assets/7403476/9990619/015fa450-6063-11e5-8ac8-9a6367e2ed77.JPG)
![connection error](https://cloud.githubusercontent.com/assets/7403476/9990623/0404b31c-6063-11e5-8ce1-27c3f359d1ee.JPG)

**Comment by inclanfunk** [comment]
Sorry to re-open but I cannot follow the workaround as I do not have the .mapbox-studio created after a fresh install...
About the command line, vendor\node index.js give a node.exe system error saying "api-ms-win-crt-runtime-l1-1-0.dll is missing" try to re-install the programme to solve this issue."

**Comment by wilhelmberg** [comment]
@inclanfunk ah, so `fresh install` means you cloned from Github?

Then you need to install the [`Visual C++ Redistributable for Visual Studio 2015`](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by inclanfunk** [comment]
Nope I download it from there:
https://www.mapbox.com/mapbox-studio-classic/#win32

**Comment by wilhelmberg** [comment]
@inclanfunk That is really strange, I just downloaded, installed and verified that the 32bit installer version works for me.

Could you check, if `api-ms-win-crt-runtime-l1-1-0.dll` is in

```
C:\Program Files\mapbox-studio\resources\app\vendor
```

and in 

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-ia32
```

**Comment by peterbodo** [comment]
Hey, I have the same problem than @inclanfunk 
@BergWerkGIS The file you have descibed is not there (with hyphens), It is with underlines:
api_ms_win_crt_runtime_l1_1_0

what to do next? :)

Thanks

**Comment by peterbodo** [comment]
Now I have renamed that file, but now the next error message does not find the win-core-timezone file.

shall I rename them all changing underlines to hyphens?

**Comment by wilhelmberg** [comment]
@peterbodo y, renaming all files in **both** directories would be necessary.

It is probably easier to install  [`Visual C++ Redistributable for Visual Studio 2015`](https://www.microsoft.com/en-us/download/details.aspx?id=48145), which should solve this, too.

**Comment by peterbodo** [comment]
@BergWerkGIS 

Thanks, I could not download Visual C++, It just did not start downloading. For any case I have renamed the files in Program Files, but I do not have a Program Files (x86) Folder at all.

I have tried to run. Now it works for 5-6 secs, before it disappears.

I have tried in CMD as well

C:\Program Files\mapbox-studio\resources\app>vendor\node index.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\nod
e-v11-win32-ia32\mapnik.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Program Files\mapbox-studio\resources\app\node_mod
ules\mapnik\lib\mapnik.js:31:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

C:\Program Files\mapbox-studio\resources\app>

**Comment by wilhelmberg** [comment]
@peterbodo sorry, typo: the second path was also meant to be `C:\Program Files`.
Could you you look again in 

```
C:\Program Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-ia32
```

and rename there, too?

**Comment by peterbodo** [comment]
@BergWerkGIS 
yep thanks.
Are these exactly the same files?
Can I just copy them?

**Comment by peterbodo** [comment]
@BergWerkGIS 
and it works now. Thx!

**Comment by inclanfunk** [comment]
Please confirm if it works renaming all the files of both folder or just
the api-ms-win-crt-runtime-l1-1-0.dll

Thanks

**Comment by peterbodo** [comment]
@inclanfunk 
Rename them all!
I mean the api ms win files

**Comment by inclanfunk** [comment]
And can I copy the renamed one from _C:\Program
Files\mapbox-studio\resources\__app\vendor_ to _C:\Program
Files\mapbox-studio\resources\app\node_modules\mapnik\lib\binding\node-v11-win32-ia32
? Thanks_

**Comment by wilhelmberg** [comment]
@peterbodo @inclanfunk 
I've re-published the 0.3.1 release.
Download again from https://www.mapbox.com/mapbox-studio-classic/ and reinstall.
Then it should work without renaming.

**Comment by inclanfunk** [comment]
Still not working.
Install without trouble, launch... start to load... 3 second later close by
itself.
Any ideas? Thanks.

**Comment by wilhelmberg** [comment]
@inclanfunk could you again try the steps outlined [above](https://github.com/mapbox/mapbox-studio-classic/issues/1466#issuecomment-141938779)?

Im especially interested in the output after `vendor\node index.js`.

**Comment by inclanfunk** [comment]
Sure...

On vendor\node index.js command, the result is:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: OK, read

**Comment by wilhelmberg** [comment]
Oh, that's a vague error message.

Are you sure, you terminated any `node.exe` and/or `mapbox-studio.exe` processes that were still running, before you tried?

I just checked with two more W7 machines and Mapbox Studio Classic worked on them.

The only things to try I can think of at the moment are (repeating `vendor\node index.js` test for each):
- delete `.mapbox-studio` folder, `%USERPROFILE%\.mapbox-studio` <- paste this into the address bar of file explorer to easily find it
- install  [`Visual C++ Redistributable for Visual Studio 2015`](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

Or try to get access to a 64bit machine.
If you want to process a lot of data with Mabox Studio Classic 32bit you could run into out-of-memory problems later on.

**Comment by wilhelmberg** [comment]
I've setup another fresh and vanilla W7 32bit VM and tested the 0.3.1 release: it worked.

**Comment by pdwelker** [comment]
Howdy
I'm new to MapBox running Windows 7 at 64bits. Downloaded and installed the latest version 0.3.1 yesterday. Same problem as above: program opens, loading circle spins then the window vanishes. 

I have worked through the above troubleshooting to no avail:
-searched %USERPROFILE%.mapbox-studio and deleted app.db.compacted
-checked Task Manager for running .exe 
-then ran the cdm and recieved this error
![image](https://cloud.githubusercontent.com/assets/14842997/10112333/5b6d2c18-63a8-11e5-9b2a-9375cd4de31f.png)

Suggestions?
Also I had the same problem as above I could not get the Visual C++ Redistributable for Visual Studio 2015 files to DL

**Comment by wilhelmberg** [comment]
@pdwelker your error means Mabox Studio Classic cannot write to `app.db`.

These are the possible reasons:
- `node.exe`/`mapbox-studio.exe` processes are still running and blocking the file
- a left over `app.db.compacted` is still there
- somehow the permissions to `%USERPROFILE%\.mapbox-studio` are screwed

Since you've already looked into 1. and 2. I suggest you
- verify 1. again
- delete `%USERPROFILE%\.mapbox-studio` completely. Make sure that it is really gone (press F5 to refresh), as Explorer sometimes doesn't report an error, even if it was not able to remove a directory completely
- run `vendor\node index` again

Any errors?

---

I just checked with the [Microsoft download for `Visual C++ Redistributable for Visual Studio 2015`](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and it worked for me.

Here are some alternative direct download links: [x64](https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2015/vcredist_x64.exe) [x86](https://mapbox.s3.amazonaws.com/windows-builds/visual-studio-runtimes/vcredist-VS2015/vcredist_x86.exe)

**Comment by pdwelker** [comment]
@BergWerkGIS after deleting the entire .mapbox-studio folder completely and re-running the vendor\node index, I received the http://localhost:3000/ in the command prompt. 

Mapbox opened and connected in the browser on the second attempt. After this I stopped (ctl+c) mapbox in the command prompt. When clicking on the shortcut Mapbox now opens successfully! It works! Thank you!

One more question: What is the http://localhost:3000/ version of Mapbox? Is it just a browser version of  Mapbox Studio?

**Comment by wilhelmberg** [comment]
@pdwelker Great, that it works now.

Mapbox Studio Classic is always the same (localhost).
The shortcut starts a bundled browser displaying localhost:3000, so that you don't have to go to the command line, start it there and then manually open your own browser.

**Comment by dosstx** [comment]
After running node index, I get the following error:

module.js:340
    throw err:

Error: Cannot find module 'C:\Users\%USERPROFILE%\mapbox-studio_032\resources\app\vendor\index'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
   at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

Any help?

**Comment by wilhelmberg** [comment]
@dosstx 

<pre>
'C:\Users\%USERPROFILE%\mapbox-studio_032\resources\app\vendor\index'
</pre>

Looks at bit unusual to me, could you describe in more detail how you installed Mapbox Studio Classic?
- Did you use the installer from here https://www.mapbox.com/mapbox-studio-classic ?
- Or did you install from source?
  - What were your exact steps? (so I can try to reproduce)

**Comment by dosstx** [comment]
@BergWerkGIS No, did not get the installer from there. My colleagues have been able to successfully get it installed, except for me.

I am in a closed environment connecting to Mapbox Atlas server. I can get Studio to open up but can't load any basemaps. During the "Connect to your mapbox account to get started" screen I have it set to connect to my employer's Atlas server. Are there logs I can check to see why it's not successfully connecting to the Atlas server?

**Comment by dosstx** [comment]
nevermind. Got it working. Changed API path to another one.

**Comment by wilhelmberg** [comment]
@dosstx Great that it works now. Thanks for letting me know (just wanted to look into this).
