### ISSUE TITLE
Building Docker image?

### ISSUE THREAD

**Issue by PeterSprague** [mapbox/mapbox-studio-classic#1534]
Has anyone successfully built and run a Docker image of mapbox-studio-classic master?

On Ubuntu 14.04 LTS
builds and runs as no-docker nodejs app

Build as Docker nodejs image

```
cd /home/user/tools/mapbox-studio-classic
docker build -t myrepo/mapbox-studio-classic-nodejs
docker run myrepo/mapbox-studio-classic-nodejs
```

Error:
module.js:340
    throw err;
          ^
Error: Cannot find module '/src/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/src/node_modules/mapnik/lib/mapnik.js:8:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Dockerfile: [adapted from  https://docs.docker.com/engine/examples/nodejs_web_app/]

```
FROM node:0.10-onbuild
#Bundle app source
COPY . /src
EXPOSE 3000
# initial run cmd
CMD ["node", "/src/index.js"]
```

**Comment by lukasmartinelli** [comment]
We are working since a half year with this Docker image on servers - works seamless.
https://github.com/osm2vectortiles/osm2vectortiles/blob/master/tools/mapbox-studio/Dockerfile
