### ISSUE TITLE
can not install mapbox

### ISSUE THREAD

**Issue by irisda** [mapbox/mapbox-studio-classic#1581]
has anyone inatall mapbox stduio?
i ahve a lot of errors and i do not know how

**Comment by alexey-gl** [comment]
I also have problems with installation.
Could anyone tell about possible solutions please.

Installation log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node8', '/usr/bin/npm-default', 'install' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose npm-session 3588b2f453809222
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall mapbox-studio@0.3.8
7 info lifecycle mapbox-studio@0.3.8~preinstall: mapbox-studio@0.3.8
8 verbose lifecycle mapbox-studio@0.3.8~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle mapbox-studio@0.3.8~preinstall: PATH: /usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/node-gyp-bin:/home/agladkov/repos/misc/mapbox-studio-classic/node_modules/.bin:/usr/lib64/mpi/gcc/openmpi/bin:/home/agladkov/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/home/agladkov/Android/Sdk/tools/:/home/agladkov/Android/Sdk/platform-tools/:/home/agladkov/Android/Sdk/tools/:/home/agladkov/Android/Sdk/platform-tools/
10 verbose lifecycle mapbox-studio@0.3.8~preinstall: CWD: /home/agladkov/repos/misc/mapbox-studio-classic
11 silly lifecycle mapbox-studio@0.3.8~preinstall: Args: [ '-c', 'node scripts/run.js scripts/vendor-node.sh' ]
12 silly lifecycle mapbox-studio@0.3.8~preinstall: Returned: code: 22  signal: null
13 info lifecycle mapbox-studio@0.3.8~preinstall: Failed to exec preinstall script
14 verbose stack Error: mapbox-studio@0.3.8 preinstall: `node scripts/run.js scripts/vendor-node.sh`
14 verbose stack Exit status 22
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/index.js:285:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm8/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid mapbox-studio@0.3.8
16 verbose cwd /home/agladkov/repos/misc/mapbox-studio-classic
17 verbose Linux 4.15.13-1-default
18 verbose argv "/usr/bin/node8" "/usr/bin/npm-default" "install"
19 verbose node v8.10.0
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 22
23 error mapbox-studio@0.3.8 preinstall: `node scripts/run.js scripts/vendor-node.sh`
23 error Exit status 22
24 error Failed at the mapbox-studio@0.3.8 preinstall script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by georgbachmann** [comment]
I also can't install... did you find a solution yet?
For me its

```
Failed to execute '/usr/local/Cellar/node/10.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/georgbachmann/Desktop/mapbox-studio-classic/mapbox-studio-classic/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/Users/georgbachmann/Desktop/mapbox-studio-classic/mapbox-studio-classic/node_modules/gdal/lib/binding' (1)
  CC(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/osr_cs_wkt_parser.o install script
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/gml2ogrgeometry.oc install script
In file included from ../deps/libgdal/gdal/ogr/gml2ogrgeometry.cpp:43:led to exec install script
In file included from /usr/local/include/ogr_geometry.h:35:
In file included from /usr/local/include/cpl_conv.h:36:
/usr/local/include/cpl_vsi.h:95:37: error: C++ requires a type specifier for all declarations
int CPL_DLL     VSIFPrintf( FILE *, CPL_FORMAT_STRING(const char *), ... ) EXPERIMENTAL_CPL_WARN_UNUSED_RESULT CPL_PRINT_FUNC_FORMAT(2, 3);
                                    ^
/usr/local/include/cpl_vsi.h:95:112: error: format argument not a string type
int CPL_DLL     VSIFPrintf( FILE *, CPL_FORMAT_STRING(const char *), ... ) EXPERIMENTAL_CPL_WARN_UNUSED_RESULT CPL_PRINT_FUNC_FORMAT(2, 3);
                                                                                                               ^                     ~
../deps/libgdal/gdal/port/cpl_port.h:580:70: note: expanded from macro 'CPL_PRINT_FUNC_FORMAT'
#define CPL_PRINT_FUNC_FORMAT( format_idx, arg_idx )  __attribute__((__format__ (__printf__, format_idx, arg_idx)))
                                                                     ^                       ~~~~~~~~~~
In file included from ../deps/libgdal/gdal/ogr/gml2ogrgeometry.cpp:43:
In file included from /usr/local/include/ogr_geometry.h:35:
In file included from /usr/local/include/cpl_conv.h:36:
/usr/local/include/cpl_vsi.h:170:42: error: C++ requires a type specifier for all declarations
int CPL_DLL     VSIFPrintfL( VSILFILE *, CPL_FORMAT_STRING(const char *), ... ) EXPERIMENTAL_CPL_WARN_UNUSED_RESULT CPL_PRINT_FUNC_FORMAT(2, 3);
                                         ^
/usr/local/include/cpl_vsi.h:170:117: error: format argument not a string type
int CPL_DLL     VSIFPrintfL( VSILFILE *, CPL_FORMAT_STRING(const char *), ... ) EXPERIMENTAL_CPL_WARN_UNUSED_RESULT CPL_PRINT_FUNC_FORMAT(2, 3);
                                                                                                                    ^                     ~
../deps/libgdal/gdal/port/cpl_port.h:580:70: note: expanded from macro 'CPL_PRINT_FUNC_FORMAT'
#define CPL_PRINT_FUNC_FORMAT( format_idx, arg_idx )  __attribute__((__format__ (__printf__, format_idx, arg_idx)))
                                                                     ^                       ~~~~~~~~~~
In file included from ../deps/libgdal/gdal/ogr/gml2ogrgeometry.cpp:43:
In file included from /usr/local/include/ogr_geometry.h:35:
In file included from /usr/local/include/cpl_conv.h:36:
/usr/local/include/cpl_vsi.h:218:57: error: unknown type name 'CSLConstList'
char CPL_DLL *VSIGetSignedURL( const char* pszFilename, CSLConstList papszOptions );
                                                        ^
In file included from ../deps/libgdal/gdal/ogr/gml2ogrgeometry.cpp:43:
In file included from /usr/local/include/ogr_geometry.h:35:
In file included from /usr/local/include/cpl_conv.h:37:
/usr/local/include/cpl_error.h:139:61: error: C++ requires a type specifier for all declarations
void CPL_DLL CPLError(CPLErr eErrClass, CPLErrorNum err_no, CPL_FORMAT_STRING(const char *fmt), ...)  CPL_PRINT_FUNC_FORMAT (3, 4);
                                                            ^
/usr/local/include/cpl_error.h:139:103: error: format argument not a string type
void CPL_DLL CPLError(CPLErr eErrClass, CPLErrorNum err_no, CPL_FORMAT_STRING(const char *fmt), ...)  CPL_PRINT_FUNC_FORMAT (3, 4);
                                                                                                      ^                      ~
../deps/libgdal/gdal/port/cpl_port.h:580:70: note: expanded from macro 'CPL_PRINT_FUNC_FORMAT'
#define CPL_PRINT_FUNC_FORMAT( format_idx, arg_idx )  __attribute__((__format__ (__printf__, format_idx, arg_idx)))
                                                                     ^                       ~~~~~~~~~~
In file included from ../deps/libgdal/gdal/ogr/gml2ogrgeometry.cpp:43:
In file included from /usr/local/include/ogr_geometry.h:35:
In file included from /usr/local/include/cpl_conv.h:37:
/usr/local/include/cpl_error.h:171:49: error: C++ requires a type specifier for all declarations
void CPL_DLL CPL_STDCALL CPLDebug(const char *, CPL_FORMAT_STRING(const char *), ...)
                                                ^
/usr/local/include/cpl_error.h:172:5: error: format argument not a string type
    CPL_PRINT_FUNC_FORMAT(2, 3);
    ^                     ~
../deps/libgdal/gdal/port/cpl_port.h:580:70: note: expanded from macro 'CPL_PRINT_FUNC_FORMAT'
#define CPL_PRINT_FUNC_FORMAT( format_idx, arg_idx )  __attribute__((__format__ (__printf__, format_idx, arg_idx)))
                                                                     ^                       ~~~~~~~~~~
In file included from ../deps/libgdal/gdal/ogr/gml2ogrgeometry.cpp:43:led to exec install script
In file included from /usr/local/include/ogr_geometry.h:35:
/usr/local/include/cpl_conv.h:77:64: error: expected function body after function declarator
char CPL_DLL *CPLStrdup( const char * ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                               ^
/usr/local/include/cpl_conv.h:89:53: error: unknown type name 'CSLConstList' exec install script
const char CPL_DLL *CPLReadLine2L( VSILFILE *, int, CSLConstList );
                                                    ^
/usr/local/include/cpl_conv.h:90:60: error: unknown type name 'CSLConstList'
const char CPL_DLL *CPLReadLine3L( VSILFILE *, int, int *, CSLConstList );
                                                           ^
/usr/local/include/cpl_conv.h:147:71: error: expected function body after function declarator
const char CPL_DLL *CPLGetPath( const char * ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                      ^
/usr/local/include/cpl_conv.h:148:74: error: expected function body after function declarator
const char CPL_DLL *CPLGetDirname( const char * ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                         ^
/usr/local/include/cpl_conv.h:149:75: error: expected function body after function declarator
const char CPL_DLL *CPLGetFilename( const char * ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                          ^
/usr/local/include/cpl_conv.h:150:75: error: expected function body after function declarator
const char CPL_DLL *CPLGetBasename( const char * ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                          ^
/usr/local/include/cpl_conv.h:151:76: error: expected function body after function declarator
const char CPL_DLL *CPLGetExtension( const char * ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                           ^
/usr/local/include/cpl_conv.h:155:88: error: expected function body after function declarator
                                     const char *pszExtension ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                                       ^
/usr/local/include/cpl_conv.h:158:90: error: expected function body after function declarator
                                       const char *pszExtension ) CPL_WARN_UNUSED_RESULT CPL_RETURNS_NONNULL;
                                                                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated. ⠇ install: info lifecycle gdal@0.8.0~install: Failed to exec install script
make: *** [Release/obj.target/libgdal/deps/libgdal/gdal/ogr/gml2ogrgeometry.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/georgbachmann/Desktop/mapbox-studio-classic/mapbox-studio-classic/node_modules/gdal/lib/binding/gdal.node" "--module_name=gdal" "--module_path=/Users/georgbachmann/Desktop/mapbox-studio-classic/mapbox-studio-classic/node_modules/gdal/lib/binding"
gyp ERR! cwd /Users/georgbachmann/Desktop/mapbox-studio-classic/mapbox-studio-classic/node_modules/gdal
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdal@0.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdal@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by m4x-h4xx** [comment]
I want to chime in - installation is failing, build is broken.
For me, it is failing when attempting to build the native gdal library:
`node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/code/mapbox-studio-classic/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/home/user/code/mapbox-studio-classic/node_modules/gdal/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/code/mapbox-studio-classic/node_modules/gdal/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Linux 4.9.0-6-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/home/user/code/mapbox-studio-classic/node_modules/gdal/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/user/code/mapbox-studio-classic/node_modules/gdal
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.15
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/code/mapbox-studio-classic/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/home/user/code/mapbox-studio-classic/node_modules/gdal/lib/binding' (1) ../deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrlayerpool.cpp:579:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrlayerpool.o.d.raw: No such file or directory
 }
`

I will probably not attempt to build this software again - currently, their CI is failing and the project has not received any care during the last few months. Actively looking for an alternative that is receiving support.

**Comment by ajhalls** [comment]
I tried it too, seems they want everyone to use the new commercialized version.

**Comment by ma2rten** [comment]
I was able to install using an older version of node.js (v4.9.1). You can use nvm to switch between nodejs version.

However, when I tried to create a new style it crashed because it ran out of memory.

**Comment by DanielRuf** [comment]
Same here, no chance with Yarn and npm.

**Comment by DanielRuf** [comment]
This is not great.

**Comment by DanielRuf** [comment]
Well https://travis-ci.org/mapbox/mapbox-studio-classic/builds/332934634

**Comment by DanielRuf** [comment]
Ouch, just broken builds.

https://github.com/mapbox/mapbox-studio-classic/commits/mb-pages
