### ISSUE TITLE
Can't parse message of type "mapnik.vector.tile"

### ISSUE THREAD

**Issue by jqtrde** [mapbox/mapbox-studio-classic#290]
Running OSX 10.9. Receiving the following errors after both cloning and building, or with [the most recent binary](http://tilemill.s3.amazonaws.com/dev/tm2-osx-2014-04-11-689bb4e.tar.gz).

```
TM2 @ http://localhost:3000/
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)

TypeError: Cannot read property '0' of undefined
    at paramCallback (/Users/Jacques/tm2/node_modules/express/lib/router/index.js:146:30)
    at load (/Users/Jacques/tm2/index.js:167:52)
    at /Users/Jacques/tm2/index.js:182:13
    at /Users/Jacques/tm2/lib/source.js:319:29
    at Get.<anonymous> (/Users/Jacques/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:287:25)
    at Get.<anonymous> (/Users/Jacques/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:181:33)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:92:17)
    at Socket.emitTimeout (http.js:1797:10)
    at Socket.g (events.js:180:16)
```

Anyone else?

**Comment by springmeyer** [comment]
try clearing the cache: `rm -rf ~/.tilemill/v2/cache`. I presume these errors occurred due to a failed network connection and things should be working fine otherwise.

**Comment by jqtrde** [comment]
seems to work, thank you.
