### ISSUE TITLE
Win7 npm install fails @ mapnik 1.4.2

### ISSUE THREAD

**Issue by srsjojo** [mapbox/mapbox-studio-classic#312]
Hello,

I'm trying to install TileMill 2 on Windows 7 x64. npm install fails at the mapnik install section. When I type node index.js I get "Cannot find module 'mapnik'"

Thanks,
~Stephen

```
C:\Users\stsmith\Documents\tilemill2>npm install
npm WARN package.json dirty@0.9.9 No repository field.
npm http GET https://registry.npmjs.org/mapnik/1.4.2
npm http 304 https://registry.npmjs.org/mapnik/1.4.2

> mapnik@1.4.2 install C:\Users\stsmith\Documents\tilemill2\node_modules\mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-mapnik.s3-us-west-1.amazonaws.com/v1.4.2/mapn
ik-v1.4.2-node-v11-win32-x64.tar.gz
node-pre-gyp http 404 https://node-mapnik.s3-us-west-1.amazonaws.com/v1.4.2/mapn
ik-v1.4.2-node-v11-win32-x64.tar.gz
node-pre-gyp ERR! Source compile required: 404 status code downloading tarball

C:\Users\stsmith\Documents\tilemill2\node_modules\mapnik>node "C:\Users\stsmith\
Documents\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild --name=mapnik --configuration=Release --module_name=map
nik --version=1.4.2 --major=1 --minor=4 --patch=2 --runtime=node --node_abi=node
-v11 --platform=win32 --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js
 --host=https://node-mapnik.s3-us-west-1.amazonaws.com/ --module_path=C:\Users\s
tsmith\Documents\tilemill2\node_modules\mapnik\lib\binding --remote_path=v1.4.2/
 --package_name=mapnik-v1.4.2-node-v11-win32-x64.tar.gz --staged_tarball=build\s
tage\v1.4.2\mapnik-v1.4.2-node-v11-win32-x64.tar.gz --hosted_path=https://node-m
apnik.s3-us-west-1.amazonaws.com/v1.4.2/ --hosted_tarball=https://node-mapnik.s3
-us-west-1.amazonaws.com/v1.4.2/mapnik-v1.4.2-node-v11-win32-x64.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.26/node.lib
gyp http GET http://nodejs.org/dist/v0.10.26/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.26/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.26/x64/node.lib
'python' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'python -c "import os;import platform;u=platform.uname();print((u[0
] == 'Darwin' and int(u[2][0:2]) >= 13) and '-stdlib=libstdc++' not in os.enviro
n.get('CXXFLAGS','') and '-mmacosx-version-min' not in os.environ.get('CXXFLAGS'
,''))"' returned exit status 1.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\stsmith\Documents\nodejs\n
ode_modules\npm\node_modules\node-gyp\lib\configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\stsmith\\Documents\\nodejs\\node_modules\\np
m\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=mapnik" "--config
uration=Release" "--module_name=mapnik" "--version=1.4.2" "--major=1" "--minor=4
" "--patch=2" "--runtime=node" "--node_abi=node-v11" "--platform=win32" "--arch=
x64" "--target_arch=x64" "--module_main=./lib/mapnik.js" "--host=https://node-ma
pnik.s3-us-west-1.amazonaws.com/" "--module_path=C:\\Users\\stsmith\\Documents\\
tilemill2\\node_modules\\mapnik\\lib\\binding" "--remote_path=v1.4.2/" "--packag
e_name=mapnik-v1.4.2-node-v11-win32-x64.tar.gz" "--staged_tarball=build\\stage\\
v1.4.2\\mapnik-v1.4.2-node-v11-win32-x64.tar.gz" "--hosted_path=https://node-map
nik.s3-us-west-1.amazonaws.com/v1.4.2/" "--hosted_tarball=https://node-mapnik.s3
-us-west-1.amazonaws.com/v1.4.2/mapnik-v1.4.2-node-v11-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\stsmith\Documents\tilemill2\node_modules\mapnik
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=ma
pnik --configuration=Release --module_name=mapnik --version=1.4.2 --major=1 --mi
nor=4 --patch=2 --runtime=node --node_abi=node-v11 --platform=win32 --arch=x64 -
-target_arch=x64 --module_main=./lib/mapnik.js --host=https://node-mapnik.s3-us-
west-1.amazonaws.com/ --module_path=C:\Users\stsmith\Documents\tilemill2\node_mo
dules\mapnik\lib\binding --remote_path=v1.4.2/ --package_name=mapnik-v1.4.2-node
-v11-win32-x64.tar.gz --staged_tarball=build\stage\v1.4.2\mapnik-v1.4.2-node-v11
-win32-x64.tar.gz --hosted_path=https://node-mapnik.s3-us-west-1.amazonaws.com/v
1.4.2/ --hosted_tarball=https://node-mapnik.s3-us-west-1.amazonaws.com/v1.4.2/ma
pnik-v1.4.2-node-v11-win32-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\stsmith\Docume
nts\tilemill2\node_modules\mapnik\node_modules\node-pre-gyp\lib\util\compile.js:
76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:743:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:810:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\stsmith\\Documents\\tilemill2\\node
_modules\\mapnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fa
llback-to-build"
node-pre-gyp ERR! cwd C:\Users\stsmith\Documents\tilemill2\node_modules\mapnik
node-pre-gyp ERR! node -v v0.10.26
node-pre-gyp ERR! node-pre-gyp -v v0.5.6
node-pre-gyp ERR! not ok
npm ERR! mapnik@1.4.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@1.4.2 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Users\\stsmith\\Documents\\nodejs\\\\node.exe" "C:\\Users\
\stsmith\\Documents\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\stsmith\Documents\tilemill2
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\stsmith\Documents\tilemill2\npm-debug.log
npm ERR! not ok code 0

C:\Users\stsmith\Documents\tilemill2>npm install -g mapnik
npm http GET https://registry.npmjs.org/mapnik
npm http 304 https://registry.npmjs.org/mapnik
C:\Users\stsmith\AppData\Roaming\npm\mapnik-render.js -> C:\Users\stsmith\AppDat
a\Roaming\npm\node_modules\mapnik\bin\mapnik-render.js
C:\Users\stsmith\AppData\Roaming\npm\mapnik-inspect.js -> C:\Users\stsmith\AppDa
ta\Roaming\npm\node_modules\mapnik\bin\mapnik-inspect.js

> mapnik@0.7.28 install C:\Users\stsmith\AppData\Roaming\npm\node_modules\mapnik

> node-gyp rebuild


C:\Users\stsmith\AppData\Roaming\npm\node_modules\mapnik>node "C:\Users\stsmith\
Documents\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild
'python' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'python -c "import os;import platform;u=platform.uname();print((u[0
] == 'Darwin' and int(u[2][0:2]) >= 13) and '-stdlib=libstdc++' not in os.enviro
n.get('CXXFLAGS','') and '-mmacosx-version-min' not in os.environ.get('CXXFLAGS'
,''))"' returned exit status 1.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\stsmith\Documents\nodejs\n
ode_modules\npm\node_modules\node-gyp\lib\configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\stsmith\\Documents\\nodejs\\node_modules\\np
m\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\stsmith\AppData\Roaming\npm\node_modules\mapnik
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! mapnik@0.7.28 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@0.7.28 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Users\\stsmith\\Documents\\nodejs\\\\node.exe" "C:\\Users\
\stsmith\\Documents\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
"mapnik"
npm ERR! cwd C:\Users\stsmith\Documents\tilemill2
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\stsmith\Documents\tilemill2\npm-debug.log
npm ERR! not ok code 0

C:\Users\stsmith\Documents\tilemill2>node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'mapnik'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\stsmith\Documents\tilemill2\lib\tm.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

C:\Users\stsmith\Documents\tilemill2>
```

**Comment by wilhelmberg** [comment]
@srsjojo 
It looks like you are using Node x64. 
Please try again with Node x86 (node-mapnik binaries are provided for 32bit only).

**Comment by srsjojo** [comment]
Thanks for the help Wilhelm, I removed Node x64 and installed x86 and Mapnik succeeded. I re-cloned tm2 and `npm install` didn't throw any errors this time, but now I get the following errors when I try to start tm2:

```
C:\Users\stsmith\Documents\tm2>node index.js

path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.<anonymous> (C:\Users\stsmith\Documents\tm2\lib\tm.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by wilhelmberg** [comment]
@srsjojo 
Sorry, but I can't help you further. When I try, I don't even get as far as you and get some other errors.
As the main page mentions, tm2 is not yet ready to use with a stable version: 
"Experimental version of TileMill powered by vector tiles. There are currently no supported releases of this software."
If it is an option for you, you could try with Linux or try to ping one of the main contributors:
https://github.com/mapbox/tm2/graphs/contributors

**Comment by springmeyer** [comment]
Hi @srsjojo tm2 does not work yet on windows because we've not actually tried to run it on windows yet. There are going to be changes to the code needed to get it working. Closing this issue and tracking at #315. In short, please check back in a week or so.
