### ISSUE TITLE
Crashes on TMP source

### ISSUE THREAD

**Issue by ingalls** [mapbox/mapbox-studio-classic#352]
Steps to Reproduce
- Create source
- Change some settings
- Kill Tilemill
- Open Tile mill back up
- An error message will say ~/TMP/... Not found
- Click Back Button
- TM2 Crashes with

```
TM2 @ http://localhost:3000/
Error: ENOENT, open '/tmp-6d11065b/data.yml'
/Users/nick/Development/public/tm2/lib/source.js:95
        xray({
        ^
TypeError: undefined is not a function
    at done (/Users/nick/Development/public/tm2/lib/source.js:95:9)
    at Statement.<anonymous> (/Users/nick/Development/public/tm2/lib/cache.js:30:28)
```

I was using the PostGIS source specifically.

**Comment by ingalls** [comment]
##### Solution

Update NPM sources.
