### ISSUE TITLE
uploads are broken

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-studio-classic#400]
with this unhelpful message:

```
Error: You are not allowed access to tm2z uploads yet.                                        
    at app.get.res.set.content-type (/Users/i/tools/tm2/index.js:228:21)                      
    at callbacks (/Users/i/tools/tm2/node_modules/express/lib/router/index.js:161:37)         
    at middleware.auth (/Users/i/tools/tm2/lib/middleware.js:131:5)                           
    at callbacks (/Users/i/tools/tm2/node_modules/express/lib/router/index.js:161:37)         
    at param (/Users/i/tools/tm2/node_modules/express/lib/router/index.js:135:11)             
    at pass (/Users/i/tools/tm2/node_modules/express/lib/router/index.js:142:5)               

    at Router._dispatch (/Users/i/tools/tm2/node_modules/express/lib/router/index.js:170:5)   
    at Object.router (/Users/i/tools/tm2/node_modules/express/lib/router/index.js:33:10)      
    at next (/Users/i/tools/tm2/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at /Users/i/tools/tm2/node_modules/express/lib/application.js:122:9                       
```

**Comment by ian29** [comment]
i believe uploads have been broken since at least late last week some time, as @ryantroyford ran into this as well.

**Comment by skorasaurus** [comment]
I also ran into this as well (currently using f2090965854cc64f202f692ff45611efd19ff714 from yesterday) ; For what it's worth, I was able to work around it by packaging it to .tm2z and then uploading that through the mapbox.com mbtiles uploader (At mapbox.com/data)

**Comment by willwhite** [comment]
@skorasaurus did this upload workflow work for you in the past?

**Comment by camilleanne** [comment]
On another note, I do not see any errors logged anywhere until I get to mapbox.com/data and I see this:
![screen shot 2014-05-28 at 8 55 39 pm](https://cloud.githubusercontent.com/assets/3952537/3111068/1b7fbb26-e6ad-11e3-9cf4-df4e66f4989b.png)

but I had gotten this:
![screen shot 2014-05-28 at 11 13 38 pm](https://cloud.githubusercontent.com/assets/3952537/3111072/24dd59e4-e6ad-11e3-8547-3347405c8e88.png)

I also tried what @skorasaurus did, but that didn't work for me either. That image above has 2 errored uploads, one is from a direct upload from a .tm2z file, the other is from tm2.

**Comment by skorasaurus** [comment]
yes, worked for me at on May 12th as well (my only other tm2 upload still on my mapbox account), don't remember if it did before that.

**Comment by willwhite** [comment]
Thanks, @skorasaurus should be fixed now.

@camilleanne it looks like your "unpacking failed" issues are a different and is likely a problem on the unpacker side rather than an issue with tm2.

**Comment by skorasaurus** [comment]
confirmed, updated to master and am now able to upload directly to mapbox via tm2. :)
