### ISSUE TITLE
tm2 running problem: fs.js:476

### ISSUE THREAD

**Issue by guss84** [mapbox/mapbox-studio-classic#419]
Running node index.js gives me this error

fs.js:476
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:476:19)
    at Object.fs.readFileSync (fs.js:310:28)
    at /home/gus/tm2/lib/tm.js:139:37
    at Array.reduce (native)
    at Function._.reduce._.foldl._.inject (/home/gus/tm2/node_modules/underscore/underscore.js:113:28)
    at _.(anonymous function) [as reduce](/home/gus/tm2/node_modules/underscore/underscore.js:1073:39)
    at Object.<anonymous> (/home/gus/tm2/lib/tm.js:137:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by yhahn** [comment]
Not able to reproduce -- would love more details/or info.
