### ISSUE TITLE
Error: Server returned HTTP 401

### ISSUE THREAD

**Issue by jczaplew** [mapbox/mapbox-studio-classic#426]
On OS X, using both the binaries and the source install instructions, I get the same error after starting TM2 and going to localhost:3000 - 

```
Error: Server returned HTTP 401
    at Get.handleClientRequest (/Users/john/Downloads/tm2/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:151:23)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:226:10)
```

In my browser, the URL redirects to `/new/style`, and I see "Error Server returned HTTP 401". I haven't worked with TM2 before, so I'm not sure if I'm doing something wrong or if there is something wrong with the current version. Any and all assistance would be appreciated!

**Comment by yhahn** [comment]
@jczaplew as a stopgap hop to `localhost:3000/unauthorize` to reset your TM2 oauth credentials.

Will look into a fix here shortly.

**Comment by jczaplew** [comment]
@yhahn That worked and I'm up and running. Thanks! Should this be considered resolved?

**Comment by yhahn** [comment]
Yep, closing.
