### ISSUE TITLE
Tilemill 2 on OS X install fails at npm install

### ISSUE THREAD

**Issue by pkorac** [mapbox/mapbox-studio-classic#48]
I'm trying to install the new TileMill 2 on my OS x 10.7.4 machine, but the install fails when I run the npm install command and of-course later the node index.js doesn't work either.

Here's the error code:

```

> mapnik-vector-tile@0.2.3 install /Users/peko6107/Documents/developer/tm2/tm2/node_modules/mapnik/node_modules/mapnik-vector-tile
> protoc -Iproto/ --cpp_out=./src/ ./proto/vector_tile.proto


> mapnik@1.1.1 install /Users/peko6107/Documents/developer/tm2/tm2/node_modules/mapnik
> node-gyp rebuild


> sqlite3@2.1.14 install /Users/peko6107/Documents/developer/tm2/tm2/node_modules/mbtiles/node_modules/sqlite3
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/generic-pool

> eio@0.2.1 install /Users/peko6107/Documents/developer/tm2/tm2/node_modules/tilelive-bridge/node_modules/eio
> node-gyp rebuild

/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:415:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/peko6107/Documents/developer/tm2/tm2/node_modules/mapnik
gyp ERR! node -v v0.10.7
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! weird error 1
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/peko6107/Documents/developer/tm2/tm2/node_modules/mbtiles/node_modules/sqlite3
gyp ERR! node -v v0.10.7
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/peko6107/Documents/developer/tm2/tm2/node_modules/tilelive-bridge/node_modules/eio
gyp ERR! node -v v0.10.7
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! not ok code 0
```

And here's what node says after running index.js:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'tilelive-bridge'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/peko6107/Documents/developer/tm2/tm2/lib/source.js:11:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by springmeyer** [comment]
`mapnik-config: command not found` is the relevant error, which indicates that you did not install Mapnik, which is required for TileMill 2.

**Comment by pkorac** [comment]
Thanks
I've just noticed that when I run the `brew install mapnik || brew upgrade mapnik` it doesn't install it.
It must be homebrew/macports issue I get this error:

```

Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Downloading http://mapnik.s3.amazonaws.com/dist/v2.2.0/mapnik-v2.2.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/mapnik-2.2.0.tar.bz2
==> /usr/bin/python scons/scons.py configure CC="cc" CXX="c++" JOBS=2 PREFIX=/us

To view overall SCons help options:
    $ python scons/scons.py --help-options or -H

More info: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation

READ THIS: https://github.com/mxcl/homebrew/wiki/troubleshooting

Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
Error: mapnik not installed

```

I'll try to uninstall macports and try again

**Comment by springmeyer** [comment]
okay, thanks for the details. When you try to build mapnik again, do `brew install --verbose mapnik` and if you hit any trouble paste the entire terminal output to a gist. There was a report of the mapnik brew install not working today over at https://github.com/mapnik/mapnik/issues/1957 (which is still unsolved), so if you hit this I'll want as many details as possible.

**Comment by pkorac** [comment]
Uninstalled macports( using [this](http://bitboxer.de/2010/06/03/moving-from-macports-to-homebrew/) technique ), still not solved. Here's the terminal output:

```
Peters-MacBook-Pro-2:tm2 peko6107$ brew install --verbose mapnik
==> Downloading http://mapnik.s3.amazonaws.com/dist/v2.2.0/mapnik-v2.2.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/mapnik-2.2.0.tar.bz2
tar xf /Library/Caches/Homebrew/mapnik-2.2.0.tar.bz2
brew: Appending to PYTHONPATH: /usr/local/Cellar/mapnik/2.2.0/lib/python2.7/site-packages
==> /usr/bin/python scons/scons.py configure CC="cc" CXX="c++" JOBS=2 PREFIX=/usr/local/Cellar/mapnik/2.2.0 ICU_INCLUDES=/usr/local/opt/icu4c/include ICU_LIBS=/usr/local/opt/icu4c/lib PYTHON_PREFIX=/usr/local/Cellar/mapnik/2.2.0 JPEG_INCLUDES=/usr/local/opt/jpeg/include JPEG_LIBS=/usr/local/opt/jpeg/lib TIFF_INCLUDES=/usr/local/opt/libtiff/include TIFF_LIBS=/usr/local/opt/libtiff/lib BOOST_INCLUDES=/usr/local/opt/boost/include BOOST_LIBS=/usr/local/opt/boost/lib PROJ_INCLUDES=/usr/local/opt/proj/include PROJ_LIBS=/usr/local/opt/proj/lib CAIRO=False
/usr/bin/python scons/scons.py configure CC="cc" CXX="c++" JOBS=2 PREFIX=/usr/local/Cellar/mapnik/2.2.0 ICU_INCLUDES=/usr/local/opt/icu4c/include ICU_LIBS=/usr/local/opt/icu4c/lib PYTHON_PREFIX=/usr/local/Cellar/mapnik/2.2.0 JPEG_INCLUDES=/usr/local/opt/jpeg/include JPEG_LIBS=/usr/local/opt/jpeg/lib TIFF_INCLUDES=/usr/local/opt/libtiff/include TIFF_LIBS=/usr/local/opt/libtiff/lib BOOST_INCLUDES=/usr/local/opt/boost/include BOOST_LIBS=/usr/local/opt/boost/lib PROJ_INCLUDES=/usr/local/opt/proj/include PROJ_LIBS=/usr/local/opt/proj/lib CAIRO=False
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Darwin in *release mode*...
Checking for freetype-config... no
Checking for xml2-config... yes
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... no
Could not find required header or shared library for png
Checking for C library tiff... yes
Checking for ICU version >= 4.2... found: icu 51.1
(cached) Searching for boost libs and headers... (cached) 
Found boost libs: /usr/local/opt/boost/lib
Found boost headers: /usr/local/opt/boost/include
Found boost lib name extension: -mt
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_54
Checking for C++ library boost_system-mt... yes
Checking for C++ library boost_filesystem-mt... yes
Checking for C++ library boost_regex-mt... yes
Checking for C++ library boost_program_options-mt... yes
Checking for C++ library boost_thread-mt... yes
Checking if boost_regex was built with ICU unicode support... (cached) no
Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for C library sqlite3... yes
Checking if SQLite supports RTREE... (cached) yes
Checking if gdal is ogr enabled... no
Checking for pg_config... yes
Checking for gdal-config --libs... error: no result
no
Not building with cairo support, pass CAIRO=True to enable
Checking for C++ header file boost/python/detail/config.hpp... yes
Not building with pycairo support, pass CAIRO=True to enable

Exiting... the following required dependencies were not found:
   - freetype-config (freetype-config program | try setting FREETYPE_CONFIG SCons option)
   - png (PNG C library | configure with PNG_LIBS & PNG_INCLUDES)

See '/private/tmp/mapnik-N5Pv/mapnik-v2.2.0/config.log' for details on possible problems.

Also, these OPTIONAL dependencies were not found:
   - boost_regex_icu (libboost_regex built with optional ICU unicode support is needed for unicode regex support in mapnik.)
   - ogr (OGR-enabled GDAL C++ Library | configured using gdal-config program | try setting GDAL_CONFIG SCons option | more info: https://github.com/mapnik/mapnik/wiki/OGR)
   - gdal-config (gdal-config program | try setting GDAL_CONFIG SCons option)

Set custom paths to these libraries and header files on the command-line or in a file called 'config.py'
    ie. $ python scons/scons.py BOOST_INCLUDES=/usr/local/include BOOST_LIBS=/usr/local/lib

Once all required dependencies are found a local 'config.py' will be saved and then install:
    $ sudo python scons/scons.py install

To view available path variables:
    $ python scons/scons.py --help or -h

To view overall SCons help options:
    $ python scons/scons.py --help-options or -H

More info: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation
==> Configuration
HOMEBREW_VERSION: 0.9.4
HEAD: da774ad4d9a795911dd2ec44f6b9f6b808ae7240
CPU: quad-core 64-bit arrandale
OS X: 10.7.5-x86_64
Xcode: 4.6.3
X11: 2.6.5 => /usr/X11
==> ENV
HOMEBREW_CC: clang
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/icu4c:/usr/local:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/Headers:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/include/apache2:/usr/X11/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/Headers
CMAKE_LIBRARY_PATH: /usr/X11/lib
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/X11/lib/pkgconfig:/usr/X11/share/pkgconfig
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
OBJC: cc
PATH: /usr/local/Library/ENV/4.3:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/proj/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/jpeg/bin:/usr/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: mapnik did not build
Logs:       /Users/peko6107/Library/Logs/Homebrew/mapnik/config.log

Peters-MacBook-Pro-2:tm2 peko6107$ 
```

**Comment by springmeyer** [comment]
hmm, looks like a 10.7 <-> homebrew formula dependency issue. Try doing:

``` sh
brew install libpng freetype
```

Then again trying:

``` sh
brew install --verbose mapnik
```

**Comment by pkorac** [comment]
The two libraries installed ok, however the stubborn error still persists:

```

Peters-MacBook-Pro-2:~ peko6107$ brew install --verbose mapnik
==> Downloading http://mapnik.s3.amazonaws.com/dist/v2.2.0/mapnik-v2.2.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/mapnik-2.2.0.tar.bz2
tar xf /Library/Caches/Homebrew/mapnik-2.2.0.tar.bz2
brew: Appending to PYTHONPATH: /usr/local/Cellar/mapnik/2.2.0/lib/python2.7/site-packages
==> /usr/bin/python scons/scons.py configure CC="cc" CXX="c++" JOBS=2 PREFIX=/usr/local/Cellar/mapnik/2.2.0 ICU_INCLUDES=/usr/local/opt/icu4c/include ICU_LIBS=/usr/local/opt/icu4c/lib PYTHON_PREFIX=/usr/local/Cellar/mapnik/2.2.0 JPEG_INCLUDES=/usr/local/opt/jpeg/include JPEG_LIBS=/usr/local/opt/jpeg/lib TIFF_INCLUDES=/usr/local/opt/libtiff/include TIFF_LIBS=/usr/local/opt/libtiff/lib BOOST_INCLUDES=/usr/local/opt/boost/include BOOST_LIBS=/usr/local/opt/boost/lib PROJ_INCLUDES=/usr/local/opt/proj/include PROJ_LIBS=/usr/local/opt/proj/lib CAIRO=False
/usr/bin/python scons/scons.py configure CC="cc" CXX="c++" JOBS=2 PREFIX=/usr/local/Cellar/mapnik/2.2.0 ICU_INCLUDES=/usr/local/opt/icu4c/include ICU_LIBS=/usr/local/opt/icu4c/lib PYTHON_PREFIX=/usr/local/Cellar/mapnik/2.2.0 JPEG_INCLUDES=/usr/local/opt/jpeg/include JPEG_LIBS=/usr/local/opt/jpeg/lib TIFF_INCLUDES=/usr/local/opt/libtiff/include TIFF_LIBS=/usr/local/opt/libtiff/lib BOOST_INCLUDES=/usr/local/opt/boost/include BOOST_LIBS=/usr/local/opt/boost/lib PROJ_INCLUDES=/usr/local/opt/proj/include PROJ_LIBS=/usr/local/opt/proj/lib CAIRO=False
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Darwin in *release mode*...
Checking for freetype-config... no
Checking for xml2-config... yes
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... no
Could not find required header or shared library for png
Checking for C library tiff... yes
Checking for ICU version >= 4.2... found: icu 51.1
(cached) Searching for boost libs and headers... (cached) 
Found boost libs: /usr/local/opt/boost/lib
Found boost headers: /usr/local/opt/boost/include
Found boost lib name extension: -mt
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_54
Checking for C++ library boost_system-mt... yes
Checking for C++ library boost_filesystem-mt... yes
Checking for C++ library boost_regex-mt... yes
Checking for C++ library boost_program_options-mt... yes
Checking for C++ library boost_thread-mt... yes
Checking if boost_regex was built with ICU unicode support... (cached) no
Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for C library sqlite3... yes
Checking if SQLite supports RTREE... (cached) yes
Checking if gdal is ogr enabled... no
Checking for pg_config... yes
Checking for gdal-config --libs... error: no result
no
Not building with cairo support, pass CAIRO=True to enable
Checking for C++ header file boost/python/detail/config.hpp... yes
Not building with pycairo support, pass CAIRO=True to enable

Exiting... the following required dependencies were not found:
   - freetype-config (freetype-config program | try setting FREETYPE_CONFIG SCons option)
   - png (PNG C library | configure with PNG_LIBS & PNG_INCLUDES)

See '/private/tmp/mapnik-PQZy/mapnik-v2.2.0/config.log' for details on possible problems.

Also, these OPTIONAL dependencies were not found:
   - boost_regex_icu (libboost_regex built with optional ICU unicode support is needed for unicode regex support in mapnik.)
   - ogr (OGR-enabled GDAL C++ Library | configured using gdal-config program | try setting GDAL_CONFIG SCons option | more info: https://github.com/mapnik/mapnik/wiki/OGR)
   - gdal-config (gdal-config program | try setting GDAL_CONFIG SCons option)

Set custom paths to these libraries and header files on the command-line or in a file called 'config.py'
    ie. $ python scons/scons.py BOOST_INCLUDES=/usr/local/include BOOST_LIBS=/usr/local/lib

Once all required dependencies are found a local 'config.py' will be saved and then install:
    $ sudo python scons/scons.py install

To view available path variables:
    $ python scons/scons.py --help or -h

To view overall SCons help options:
    $ python scons/scons.py --help-options or -H

More info: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation
==> Configuration
HOMEBREW_VERSION: 0.9.4
HEAD: da774ad4d9a795911dd2ec44f6b9f6b808ae7240
CPU: quad-core 64-bit arrandale
OS X: 10.7.5-x86_64
Xcode: 4.6.3
X11: 2.6.5 => /usr/X11
==> ENV
HOMEBREW_CC: clang
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/icu4c:/usr/local:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/Headers:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/include/apache2:/usr/X11/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/Headers
CMAKE_LIBRARY_PATH: /usr/X11/lib
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/proj/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/System/Library/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/X11/lib/pkgconfig:/usr/X11/share/pkgconfig
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
OBJC: cc
PATH: /usr/local/Library/ENV/4.3:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/proj/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/jpeg/bin:/usr/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: mapnik did not build
Logs:       /Users/peko6107/Library/Logs/Homebrew/mapnik/config.log

Peters-MacBook-Pro-2:~ peko6107$ 

```

**Comment by springmeyer** [comment]
okay, sorry this is not working. pretty odd. Can you try:

```
brew install https://gist.github.com/springmeyer/6057402/raw/9174ffa6a2780d83673be4bbef9fb37831795834/mapnik.rb
```

Which will install mapnik with a slightly modified formula which is more explicit about the paths needed for libpng and freetype: https://gist.github.com/springmeyer/6057402

**Comment by aaronlidman** [comment]
It's been a while. Feel free to open another issue if you're still having issues.
