### ISSUE TITLE
`npm install` fails to untar (what appears to be valid tar archive)

### ISSUE THREAD

**Issue by artemp** [mapbox/mapbox-studio-classic#5]
``` bash
npm ERR! tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622464342974126/tmp.tgz
npm ERR! tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622464342974126/tmp.tgz
npm ERR! tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622464342974126/tmp.tgz
npm ERR! tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622464342974126/tmp.tgz
npm ERR! Error: invalid tar file
npm ERR!     at Extract.Parse._startEntry (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:144:13)
npm ERR!     at Extract.Parse._process (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:125:12)
npm ERR!     at BlockStream.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:46:8)
npm ERR!     at BlockStream.EventEmitter.emit (events.js:96:17)
npm ERR!     at BlockStream._emitChunk (/opt/node/lib/node_modules/npm/node_modules/block-stream/block-stream.js:145:10)
npm ERR!     at BlockStream.resume (/opt/node/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/opt/node/lib/node_modules/npm/node_modules/fstream/lib/reader.js:252:34)
npm ERR!     at Entry.Parse._startEntry._entry (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:256:8)
npm ERR!     at Entry.EventEmitter.emit (events.js:93:17)
npm ERR!     at Entry.inherits.resume (/opt/node/lib/node_modules/npm/node_modules/tar/lib/entry.js:91:10)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.3.0
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install"
npm ERR! cwd /Users/artem/Projects/mapbox/tm2
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14
npm ERR! tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622464342974126/tmp.tgz
npm ERR! tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622464342974126/tmp.tgz
npm http 304 https://registry.npmjs.org/chrono
npm http 304 https://registry.npmjs.org/tilejson
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/artem/Projects/mapbox/tm2/npm-debug.log
npm ERR! not ok code 0
macbook:tm2 artem$ emacs /Users/artem/Projects/mapbox/tm2/npm-debug.log

6686 error tar.unpack untar error /var/folders/83/rt7rty5j1v3gj5kpymxsq_0w0000gn/T/npm-4065/1365415995318-0.24622\
464342974126/tmp.tgz
6687 silly gunzTarPerm extractEntry test/data/Clément/long_lat.prj
6688 silly gunzTarPerm modified mode [ 'test/data/Clément/long_lat.prj', 436, 420 ]
6689 silly lockFile 4e826426-mapbox-node-mapnik-data-tile-git git@github.com:mapbox/node-mapnik-data-tile.git
6690 error Error: invalid tar file
6690 error     at Extract.Parse._startEntry (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:144:13)
6690 error     at Extract.Parse._process (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:125:12)
6690 error     at BlockStream.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:46:8)
6690 error     at BlockStream.EventEmitter.emit (events.js:96:17)
6690 error     at BlockStream._emitChunk (/opt/node/lib/node_modules/npm/node_modules/block-stream/block-stream.j\
s:145:10)
6690 error     at BlockStream.resume (/opt/node/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58\
:15)
6690 error     at Extract.Reader.resume (/opt/node/lib/node_modules/npm/node_modules/fstream/lib/reader.js:252:34\
)
6690 error     at Entry.Parse._startEntry._entry (/opt/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:25\
6:8)
6690 error     at Entry.EventEmitter.emit (events.js:93:17)
6690 error     at Entry.inherits.resume (/opt/node/lib/node_modules/npm/node_modules/tar/lib/entry.js:91:10)
6691 error If you need help, you may report this log at:
6691 error     <http://github.com/isaacs/npm/issues>
6691 error or email it to:
6691 error     <npm-@googlegroups.com>
6692 error System Darwin 12.3.0
6693 error command "/opt/node/bin/node" "/opt/node/bin/npm" "install"
6694 error cwd /Users/artem/Projects/mapbox/tm2
6695 error node -v v0.8.22
6696 error npm -v 1.2.14
6697 verbose exit [ 1, true ]
```

**Comment by artemp** [comment]
`npm cache clean` <-- doesn't help

**Comment by springmeyer** [comment]
Usually when I see something like this it indicates a download is failing due to something like a github timeout. I have to step through each install to figure out the culprit. In this case however I see a line about the Unicode test I added to node-mapnik. So maybe that is messing up npm.

**Comment by springmeyer** [comment]
This turned out to be due to the paths that use non latin characters inside the node-mapnik tests. I could not replicate on my machine, but removing the tests from the node-mapnik-data-tile repo worked around the issue for @artemp. The tests are still in node-mapnik proper so @artemp will still get hit by this if he tries to install node-mapnik from github, but should be safe when pulling node-mapnik from npmjs.org. I figure the bug is either in my git version that stores the paths or in node-tar, but it would take more time to figure this out than I want to spend. Will close this a track at https://github.com/mapnik/node-mapnik/issues/142
