### ISSUE TITLE
Error when canceling a source upload to mapbox

### ISSUE THREAD

**Issue by kottmann** [mapbox/mapbox-studio-classic#565]
I tried to upload a source to mapbox, after sometime I decided to click on "Cancel". Just after pressing it the following error was written to the console:

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/home/xyz/git/tm2/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at next (/home/xyz/git/tm2/node_modules/express/node_modules/connect/lib/proto.js:153:13)
    at pass (/home/xyz/git/tm2/node_modules/express/lib/router/index.js:107:24)
    at nextRoute (/home/xyz/git/tm2/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/home/xyz/git/tm2/node_modules/express/lib/router/index.js:164:11)
    at load (/home/xyz/git/tm2/lib/middleware.js:48:52)
    at /home/xyz/git/tm2/lib/middleware.js:63:13
    at /home/xyz/git/tm2/lib/source.js:364:29
    at Get.<anonymous> (/home/xyz/git/tm2/node_modules/tilejson/node_modules/get/lib/node-get/node-get.js:287:25)

**Comment by springmeyer** [comment]
perhaps related: #645
