### ISSUE TITLE
intermittent crashes while zooming/panning 

### ISSUE THREAD

**Issue by artemp** [mapbox/mapbox-studio-classic#645]
I'm getting intermittent crashes while browsing maps  (OS X):

``` bash
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/lib/response.js:518:10)
    at ServerResponse.res.cookie (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/lib/response.js:590:8)
    at done (/Applications/Mapbox Studio.app/Contents/Resources/app/lib/server.js:160:17)
    at cb (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilelive-vector/index.js:124:20)
    at sourceGet (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilelive-vector/backend.js:95:66)
    at /Applications/Mapbox Studio.app/Contents/Resources/app/lib/cache.js:44:17
    at /Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilejson/lib/tilejson.js:141:25
    at done (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilejson/lib/tilejson.js:214:13)
```

or 

``` bash
http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/lib/response.js:518:10)
    at ServerResponse.res.cookie (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/lib/response.js:590:8)
    at done (/Applications/Mapbox Studio.app/Contents/Resources/app/lib/server.js:166:13)
    at /Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilelive-vector/index.js:192:28
```

**Comment by camilleanne** [comment]
Hm. Also seeing it in Travis https://travis-ci.org/mapbox/mapbox-studio/jobs/32877720

**Comment by camilleanne** [comment]
Also running in to this error intermittently when toggling between modals -- however, can't really replicate:

```
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/Users/camille/dev/MapBox/tm2/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/Users/camille/dev/MapBox/tm2/node_modules/express/lib/response.js:518:10)
    at ServerResponse.res.cookie (/Users/camille/dev/MapBox/tm2/node_modules/express/lib/response.js:590:8)
    at done (/Users/camille/dev/MapBox/tm2/lib/server.js:166:13)
    at /Users/camille/dev/MapBox/tm2/node_modules/tilelive-vector/index.js:192:28
```

**Comment by springmeyer** [comment]
@camilleanne - thanks for looking into this. The error `Can't parse message of type` is coming out of the google protobuf parser and likely means that a truncated or otherwise corrupt tile is being passed to mapnik - which may mean some network problem / failed tile fetch is not being caught earlier on.

**Comment by tmcw** [comment]
My 2c here: looks like [vtile.parse](https://github.com/mapbox/tilelive-vector/blob/master/backend.js#L160-L163) is throwing an exception that's uncaught, causing express/connect to send out its automatic 'fail response' [before we try to set a cookie](https://github.com/mapbox/mapbox-studio/blob/mb-pages/lib/server.js#L172).

**Comment by artemp** [comment]
Looks like this one is back  - 0.1.5. zooming in/out 

```
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "mapnik.vector.tile" because it is missing required fields: (cannot determine missing fields for lite message)

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/lib/response.js:518:10)
    at ServerResponse.res.cookie (/Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/express/lib/response.js:590:8)
    at done (/Applications/Mapbox Studio.app/Contents/Resources/app/lib/server.js:190:13)
    at /Applications/Mapbox Studio.app/Contents/Resources/app/node_modules/tilelive-vector/index.js:192:28

```

**Comment by pnorman** [comment]
Also getting it, but no mentions of Protobuf

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.res.setHeader (/home/pnorman/mapbox-studio/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/home/pnorman/mapbox-studio/node_modules/express/lib/response.js:518:10)
    at ServerResponse.res.cookie (/home/pnorman/mapbox-studio/node_modules/express/lib/response.js:590:8)
    at done (/home/pnorman/mapbox-studio/lib/server.js:183:17)
    at cb (/home/pnorman/mapbox-studio/node_modules/tilelive-vector/index.js:124:20)
    at sourceGet (/home/pnorman/mapbox-studio/node_modules/tilelive-vector/backend.js:94:66)
    at /home/pnorman/mapbox-studio/lib/cache.js:60:17
    at /home/pnorman/mapbox-studio/node_modules/tilejson/lib/tilejson.js:141:25
    at done (/home/pnorman/mapbox-studio/node_modules/tilejson/lib/tilejson.js:214:13)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

I got this when zooming to an unoptimized zoom level, which Mapbox Studio said timed out after 5000ms
