### ISSUE TITLE
Object # has no method 'filter'

### ISSUE THREAD

**Issue by jczaplew** [mapbox/mapbox-studio-classic#683]
When I start Mapbox Studio, I see this error in the browser. If I log out of my Mapbox account and log back in, I still receive the error.

In the terminal it looks like this:

```
TypeError: Object #<Object> has no method 'filter'
    at Object.tm.history (/Users/john/code/mapbox-studio/lib/tm.js:136:23)
    at Object.middleware.history (/Users/john/code/mapbox-studio/lib/middleware.js:37:22)
    at middleware.latest (/Users/john/code/mapbox-studio/lib/middleware.js:77:16)
    at callbacks (/Users/john/code/mapbox-studio/node_modules/express/lib/router/index.js:161:37)
    at param (/Users/john/code/mapbox-studio/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/john/code/mapbox-studio/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/Users/john/code/mapbox-studio/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/Users/john/code/mapbox-studio/node_modules/express/lib/router/index.js:33:10)
    at next (/Users/john/code/mapbox-studio/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at /Users/john/code/mapbox-studio/node_modules/express/lib/application.js:122:9
```

**Comment by savannahjune** [comment]
I'm getting the same error. I starting seeing this after I installed the lastest version a couple days ago. In addition to the TypeError pasted above, I get these warnings when installing: 

npm WARN package.json dirty@0.9.9 No repository field.
npm WARN package.json mapbox-outdoors@1.0.0 No repository field.
npm WARN package.json mapbox-studio-default-source@1.0.0 No repository field.
npm WARN package.json mapbox-studio-default-style@1.0.0 No repository field.
npm WARN package.json osm-bright@1.0.1 No repository field.
npm WARN package.json satellite-afternoon@1.0.0 No repository field.

**Comment by yhahn** [comment]
Hm, this is a bug in a previous db format that should be fixed now but the migration doesn't appear to work for everyone. Workaround is to remove your app db -- on Mac OS X/linux:

```
rm ~/.tilemill/v2/app.db
```

**Comment by jczaplew** [comment]
This worked well. Thanks!

**Comment by savannahjune** [comment]
Worked for me as well. Thanks!
