### ISSUE TITLE
Source Upload Crashes

### ISSUE THREAD

**Issue by savannahjune** [mapbox/mapbox-studio-classic#716]
Each time I try to upload a local source to Mapbox, it fails in the 80 percents and I get this error:

```
TypeError: object is not a function
    at afterWrite (_stream_writable.js:277:3)
    at onwrite (_stream_writable.js:269:7)
    at WritableState.onwrite (_stream_writable.js:96:5)
    at Response.<anonymous> (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/s3-upload-stream/lib/s3-upload-stream.js:155:13)
    at Request.<anonymous> (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:263:18)
    at Request.callListeners (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.failRequest (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:498:10)
    at Request.<anonymous> (/Users/Savannah/mapbox-studio/node_modules/mapbox-upload/node_modules/aws-sdk/lib/request.js:484:32)
Segmentation fault: 11
```

**Comment by springmeyer** [comment]
Thanks for the report. Can you open up /Users/Savannah/Library/Logs/DiagnosticReports and look for any recent files and post them to https://gist.github.com for us to take a closer look at? If there are files there they will show what exactly crashed causing the 'segmentation fault'.

**Comment by savannahjune** [comment]
Okay, I posted two of them here: https://gist.github.com/savannahjune/cd113fc63cfac1f6aed2

Thanks!

**Comment by springmeyer** [comment]
Thanks! Looks like the segfault is a side effect of the first error 'Object is not a function'. @yhahn any idea what might cause an aws-SDK error like this?

**Comment by springmeyer** [comment]
perhaps related: https://github.com/nathanpeck/s3-upload-stream/issues/10

**Comment by yalefox** [comment]
I'm having the same problem. Any updates on when this might be fixed? Thanks!

**Comment by nathanpeck** [comment]
Hi, I'm the maintainer of s3-upload-stream. I don't think nathanpeck/s3-upload-stream#10 is relevant because that was an issue in s3-upload-stream introduced in versions 0.5.0 and fixed in version 0.6.1

mapbox-studio is using mapbox-upload, which is using s3-upload-stream version 0.4.x, so the version of s3-upload-stream being used does not contain that issue.

I can't entirely rule out an issue in s3-upload-stream, however. Perhaps the maintainer of mapbox-upload could try switching to the most recent version of s3-upload-stream?

**Comment by yhahn** [comment]
Wow @nathanpeck thanks for chiming in across projects. We'll look into updating to 0.6.1 next.

**Comment by nathanpeck** [comment]
@yhahn Sure thing. If you are able to confirm that it is an issue with s3-upload-stream let me know and I'll fix it ASAP. I haven't seen anything like this issue to date, however.

**Comment by camilleanne** [comment]
@savannahjune @yalefox I've updated Mapbox Upload to use the latest version of s3-upload-stream to rule that out as an issue -- if you wouldn't mind downloading 0.0.9 from www.mapbox.com/mapbox-studio and trying to upload a source again.
