### ISSUE TITLE
OAuthError (ETIMEDOUT) on login

### ISSUE THREAD

**Issue by MaksVasilev** [mapbox/mapbox-studio-classic#717]
1) run ./atom from console
2) press «Connect» button and login to mapbox
3) press «Allow» button to authorize mapbox-studio in your account
4) have error on console:

{ [InternalOAuthError: Failed to obtain access token]
  name: 'InternalOAuthError',
  message: 'Failed to obtain access token',
  oauthError: { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' } }

5) press «Allow» button again and have:

Error: Access denied
    at Object.app.use.passport.authenticate.session [as handle](/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/lib/oauth.js:62:14)
    at next (/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at next (/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/proto.js:165:78)
    at next (/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/proto.js:165:78)
    at Object.initialize [as handle](/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/passport/lib/middleware/initialize.js:62:5)
    at next (/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.expressInit [as handle](/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/lib/middleware.js:31:5)
    at next (/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.query [as handle](/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
    at next (/home/maks/OSM/mapbox-studio-linux-x64-v0.0.3/resources/app/node_modules/express/node_modules/connect/lib/proto.js:190:15)

OS Linux x86_64 work with squid proxy server on localhost and not have direct iternet connection.

**Comment by springmeyer** [comment]
Thanks for this report. We are working on proxy support over at #860.
