### ISSUE TITLE
Application crashes when adding new layers

### ISSUE THREAD

**Issue by flemmens** [mapbox/mapbox-studio-classic#850]
I am unable to load some data from a postgis database. It works well when adding small tables (for instance a list with countries boundaries) but when I try to add bigger tables (ie. a table containing 1M polygons with administrative regions divisions), it begins to load some parts, then the program crashes and closes itself. When I relaunch it 2-3 times, sometimes it continues to load the missing parts and finally display the entire data, but most of the time with big tables, it crashes. I also experienced frequent crashes when styling smaller tables. So, unfortunately we have to continue to work with Tilemill as the current version of studio (1.2, windows version) seems a way too unstable to use in a professional environment.

**Comment by flemmens** [comment]
And also a small thing, could you please keep the information of postgis connection as for now we have to re-enter all the parameters each time we connect a new table, it is really annoying. In Tilemill we can create favorites with connection settings, we didn't find anything like this in studio.

**Comment by yhahn** [comment]
@flemmens thanks for your notes -- we've run into stability issues between Studio + PostGIS on windows as well (vs. a very stable experience on OS X and Linux). If it's an option for you to use either OS X or Linux as a workaround it's what I would suggest until we get to the bottom of windows+postgis instability.

**Comment by flemmens** [comment]
Ok thanks, we will wait for the update then. Actually the current Windows version is absolutely not usable, it crashes every 5 min for various reasons (sources import, styling, export), we were not able to complete even a small project.

**Comment by yhahn** [comment]
@flemmens if you could send or post the `app.log` file from the `.mapbox-studio` folder in your user's home directory that would be very helpful.

I've not run into crashes like you're mentioning so your logs will definitely help for debugging what things are triggering crashes.

**Comment by flemmens** [comment]
Sure, here is the log:

Mapbox Studio @ http://localhost:3000/
Error: EPERM, readdir 'C:\Documents and Settings'
Error: EPERM, readdir 'C:\Documents and Settings'
Error: EPERM, readdir 'C:\Documents and Settings'
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Error: Failed to find font face 'Komika Hand Bold' in style 'place_label' in TextSymbolizer
Error: Failed to find font face 'Komika Hand Bold' in style 'place_label' in TextSymbolizer
Error: style.mss:44:14 variable @ff0000 is undefined
style.mss:44:14 variable @ff0000 is undefined
style.mss:44:14 variable @ff0000 is undefined
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Object.tree.Variable.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\variable.js:27:17)
    at Object.tree.Expression.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\expression.js:15:34)
    at Object.tree.Value.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\value.js:11:34)
    at Rule.tree.Rule.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\rule.js:115:20)
    at Definition.tree.Definition.symbolizersToXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:139:38)
    at Definition.tree.Definition.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:200:29)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:30:29)
Error: style.mss:45:2 Invalid code: line-width: "1;
style.mss:44:2 Invalid value for line-color, the type color is expected. ff0000 (of type keyword)  was given.
style.mss:44:2 Invalid value for line-color, the type color is expected. ff0000 (of type keyword)  was given.
style.mss:44:2 Invalid value for line-color, the type color is expected. ff0000 (of type keyword)  was given.
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Object.tree.Ruleset.flatten (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\ruleset.js:157:21)
    at Object.tree.Ruleset.flatten (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\ruleset.js:153:22)
    at Object.toList (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:246:44)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\renderer.js:100:25
    at Array.map (native)
    at Function._.map._.collect (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\node_modules\underscore\underscore.js:98:56)
    at _.(anonymous function) [as map](c:Program Files %28x86%29mapbox-studioresourcesappnode_modulescartonode_modulesunderscoreunderscore.js:1178:39)
    at Renderer.render (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\renderer.js:88:10)
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\style.js:263:16
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Error: Missing required field "table" (type=data) for layer "postgis"
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:335:19
    at Array.map (native)
    at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:306:29)
    at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
    at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
    at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
    at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
    at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
    at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
Error: Missing required field "table" (type=data) for layer "postgis"
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:335:19
    at Array.map (native)
    at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:306:29)
    at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
    at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
    at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
    at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
    at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
    at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
Error: Missing required field "table" (type=data_1) for layer "postgis"
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:335:19
    at Array.map (native)
    at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:306:29)
    at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
    at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
    at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
    at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
    at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
    at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
Error: Missing required field "table" (type=data) for layer "postgis"
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:335:19
    at Array.map (native)
    at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:306:29)
    at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
    at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
    at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
    at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
    at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
    at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
Error: Error getting stats from file. File might not exist.
    at invalid (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\mapnik-omnivore\lib\invalid.js:2:56)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\mapnik-omnivore\index.js:33:34
    at Object.oncomplete (fs.js:107:15)
Error: Error getting stats from file. File might not exist.
    at invalid (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\mapnik-omnivore\lib\invalid.js:2:56)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\mapnik-omnivore\index.js:33:34
    at Object.oncomplete (fs.js:107:15)
Mapbox Studio @ http://localhost:3000/
Error: style.mss:24:18 variable @land is undefined
style.mss:19:22 variable @land is undefined
style.mss:19:28 variable @fill4 is undefined
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Object.tree.Variable.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\variable.js:27:17)
    at Object.tree.Expression.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\expression.js:15:34)
    at Object.tree.Value.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\value.js:11:34)
    at Rule.tree.Rule.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\rule.js:115:20)
    at Definition.tree.Definition.symbolizersToXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:139:38)
    at Definition.tree.Definition.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:200:29)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:30:29)
Error: style.mss:24:18 variable @land is undefined
style.mss:19:22 variable @land is undefined
style.mss:19:28 variable @fill4 is undefined
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Object.tree.Variable.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\variable.js:27:17)
    at Object.tree.Expression.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\expression.js:15:34)
    at Object.tree.Value.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\value.js:11:34)
    at Rule.tree.Rule.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\rule.js:115:20)
    at Definition.tree.Definition.symbolizersToXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:139:38)
    at Definition.tree.Definition.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:200:29)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:30:29)
Error: style.mss:24:18 variable @land is undefined
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Object.tree.Variable.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\variable.js:27:17)
    at Object.tree.Expression.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\expression.js:15:34)
    at Object.tree.Value.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\value.js:11:34)
    at Rule.tree.Rule.ev (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\rule.js:115:20)
    at Definition.tree.Definition.symbolizersToXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:139:38)
    at Definition.tree.Definition.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:200:29)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:30:29)
Mapbox Studio @ http://localhost:3000/
Error: Error getting stats from file. File might not exist.
    at invalid (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\mapnik-omnivore\lib\invalid.js:2:56)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\mapnik-omnivore\index.js:33:34
    at Object.oncomplete (fs.js:107:15)
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Error: bad allocation
Error: bad allocation
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Error: style.mss:128:2 Invalid value for line-width, the type float is expected. [scalerank](of type field)  was given.
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Rule.tree.Rule.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\rule.js:83:24)
    at Definition.tree.Definition.symbolizersToXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:139:46)
    at Definition.tree.Definition.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:200:29)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:30:29)
    at Renderer.render (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\renderer.js:134:39)
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\style.js:263:16
    at new source (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:96:27)
Error: style.mss:128:2 Invalid value for line-width, the type float is expected. [scalerank]*0.8 (of type field)  was given.
    at Object.env.error (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\parser.js:235:55)
    at Rule.tree.Rule.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\rule.js:83:24)
    at Definition.tree.Definition.symbolizersToXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:139:46)
    at Definition.tree.Definition.toXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\definition.js:200:29)
    at c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\tree\style.js:30:29)
    at Renderer.render (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\carto\lib\carto\renderer.js:134:39)
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\style.js:263:16
    at new source (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:96:27)
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Error: Postgis Plugin: ERREUR:  la relation « cepages » n'existe pas
LINE 1: SELECT \* FROM cepages LIMIT 0
                      ^

in executeQuery Full sql was: 'SELECT \* FROM cepages LIMIT 0'

```
at data.vector_layers (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:366:26)
at Array.reduce (native)
at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:356:22)
at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
```

[Error: PostGIS: geometry name lookup failed for table 'vins.cepages'. Please manually provide the 'geometry_field' parameter or add an entry in the geometry_columns for 'vins.cepages'.] undefined
[Error: PostGIS: geometry name lookup failed for table 'vins.cepages'. Please manually provide the 'geometry_field' parameter or add an entry in the geometry_columns for 'vins.cepages'.] undefined
Error: Postgis Plugin: Bad connection
Connection string: 'host=locahost dbname=postgis user=postgres connect_timeout=4'

```
at data.vector_layers (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:366:26)
at Array.reduce (native)
at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:356:22)
at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
```

Error: Postgis Plugin: Bad connection
Connection string: 'host=locahost port=5436 dbname=postgis user=postgres connect_timeout=4'

```
at data.vector_layers (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:366:26)
at Array.reduce (native)
at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:356:22)
at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
```

Error: Missing required field "file" (type=data) for layer "sqlite"
    at c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:335:19
    at Array.map (native)
    at Function.source.normalize (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:306:29)
    at Function.source.save (c:\Program Files (x86)\mapbox-studio\resources\app\lib\source.js:176:23)
    at middleware.writeSource (c:\Program Files (x86)\mapbox-studio\resources\app\lib\middleware.js:162:12)
    at callbacks (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:161:37)
    at param (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:135:11)
    at pass (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:170:5)
    at Object.router (c:\Program Files (x86)\mapbox-studio\resources\app\node_modules\express\lib\router\index.js:33:10)
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/
Mapbox Studio @ http://localhost:3000/

**Comment by springmeyer** [comment]
hi @flemmens  - Mapbox Studo v0.2.0 was just released (you can download it from https://www.mapbox.com/mapbox-studio/). I would be interested to know if this helps resolve some of the instability issues you have been seeing. As far as the logs you provided above those errors do not look directly related to the crashes but rather look like invalid styling or datasource options. I presume you were able to worked around by providing new inputs in the UI. Let me know if not and if I can help you resolve any issues.

**Comment by springmeyer** [comment]
bump @flemmens - have you had a chance to try v0.2.0 yet?

**Comment by flemmens** [comment]
Hi Dane,

We do not use studio anymore, this product does not fit our needs. We use a custom version of Tilemill and several tools we have designed.

**Comment by springmeyer** [comment]
@flemmens okay, thanks for the followup.
