### ISSUE TITLE
Trouble installing mapbox-studio on ubuntu precise 12.04LTS 64-bit

### ISSUE THREAD

**Issue by blm14** [mapbox/mapbox-studio-classic#967]
Output from npm install --build-from-source is here:  http://pastebin.com/KW7Bgx5r

It looks like there are two sections with errors. One where it complains about the version of sqlite3, and the second where it tells me that there is no directory /mapbox-studio/node_modules/mapnik. 

Any help appreciated. Thanks!

**Comment by yhahn** [comment]
@blm14 check out the section on ubuntu 12.04 here:

https://github.com/mapbox/mapbox-studio#depends

**Comment by blm14** [comment]
I had already done this:

sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -q
sudo apt-get install -y libstdc++6

Before I did the install shown in the pastebin above. Does that mean I am SOL and need to upgrade to 14.04LTS?

**Comment by yhahn** [comment]
@blm14 have you tried just `npm install` instead of `npm install --build from source` ?

**Comment by blm14** [comment]
here is the output without the --build-from-source directive:

http://pastebin.com/3fUZmKTN

and here is the content of npm-debug.log from running it without --build-from-source directive:

http://paste.ubuntu.com/8706957/

**Comment by yhahn** [comment]
@blm14 it looks like you are using node v0.8.x which is ancient. Mapbox Studio requires node v0.10.x -- you can grab it from http://www.nodejs.org

**Comment by blm14** [comment]
that's the version of node packaged with precise LOL! OK I just Chris Lea's NODEjs repo and am trying again. It installed a much newer node and a much newer npm. Lets see what happpens

**Comment by blm14** [comment]
OK, getting further. This is the output of install:

``` sh
$ npm install

> mapbox-studio@0.1.6 preinstall /home/ben/mapbox-studio
> node scripts/run.js scripts/vendor-node.sh

Running /home/ben/mapbox-studio/scripts/vendor-node.sh
vendor node already exists


npm WARN package.json dirty@0.9.9 No repository field.
npm WARN package.json mapbox-studio-comic@1.0.1 No repository field.
npm WARN package.json mapbox-studio-default-source@1.0.0 No repository field.
npm WARN package.json mapbox-studio-default-style@1.0.0 No repository field.
npm WARN package.json mapbox-studio-highcontrast@1.0.6 No repository field.
npm WARN package.json mapbox-studio-light@1.1.0 No repository field.
npm WARN package.json mapbox-studio-mapbox-outdoors@1.0.1 No repository field.
npm WARN package.json mapbox-studio-osm-bright@1.0.2 No repository field.
npm WARN package.json mapbox-studio-pencil@1.0.1 No repository field.
npm WARN package.json mapbox-studio-pirates@1.0.0 No repository field.
npm WARN package.json mapbox-studio-run-bike-and-hike@1.0.2 No repository field.
npm WARN package.json mapbox-studio-satellite-afternoon@1.0.1 No repository field.
npm WARN package.json mapbox-studio-wheatpaste@1.0.1 No repository field.
|
> mapbox-studio@0.1.6 postinstall /home/ben/mapbox-studio
> npm dedupe node-pre-gyp
```

Now it is failing on the start:

``` sh
$ npm start

> mapbox-studio@0.1.6 start /home/ben/mapbox-studio
> ./index.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/home/ben/mapbox-studio/node_modules/mapnik-omnivore/node_modules/srs/lib/binding/node-v11-linux-x64/srs.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ben/mapbox-studio/node_modules/mapnik-omnivore/node_modules/srs/lib/srs.js:18:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! mapbox-studio@0.1.6 start: `./index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the mapbox-studio@0.1.6 start script.
npm ERR! This is most likely a problem with the mapbox-studio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapbox-studio
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/ben/mapbox-studio
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ben/mapbox-studio/npm-debug.log
npm ERR! not ok code 0
```

**Comment by yhahn** [comment]
Ok, give it a clean slate and one more go

```
rm -rf node_modules
npm install
```

Sometimes stale files are leftover from previous build attempts that can prevent a new install attempt from trying all the things.

**Comment by blm14** [comment]
Yup I realized that there was probably something bad from the prior earlier version of node and I just wiped the entire git and redownloaded and and now it looks like it's working.
